Logical operators
javascript-tutorial/fa.javascript.info pull request #100
Opened 2021-03-26 15:12 UTC by mahdiHashemi14

Please read the description of article.md and solution.md of task 8 "if question".
Please review and comment / commit if anything is wrong

2021-03-26 20:15 UTC, mahdyar requested changes

2021-03-26 20:15 UTC, mahdyar commented on 1-js/02-first-steps/11-logical-operators/article.md
> +## || (OR یا)
There is no need for Persian translation.

2021-03-26 20:15 UTC, mahdyar commented on 1-js/02-first-steps/11-logical-operators/article.md
> +alert( false || false ); // false اشتباه
Use either `true` or `درست`, not both of them.
Use either `false` or `اشتباه`, not both of them.

2021-03-26 20:15 UTC, mahdyar commented on 1-js/02-first-steps/11-logical-operators/article.md
> +اولویت NOT `!` بالاترین اولویت بین عملگر های منطقی دارد، بنابراین همیشه اول اجرا می شود، قبل از `&&` یا `||`.
The sentence readability could be better:
``عملگر NOT `!` بالاترین اولویت را بین عملگرهای منطقی دارد،``

2021-03-26 20:15 UTC, mahdyar commented on 1-js/02-first-steps/11-logical-operators/article.md
> +  alert( 'The office is closed.' ); // آخر هفته است
`The office is closed.` should also be translated.

2021-03-27 10:33 UTC, mahdiHashemi14 commented
Thank you for your review, @mahdyar

2021-03-27 10:33 UTC, mahdiHashemi14 commented
/done

2021-03-27 10:55 UTC, mahdyar approved these changes
Thank you, @mahdiHashemi14!

2021-03-27 10:57 UTC, merged