Translate aticle.md
javascript-tutorial/fa.javascript.info pull request #101
Opened 2021-03-28 06:37 UTC by emadPoursina

Translation is done. Please review and commit if anything is wrong.

2021-03-28 07:46 UTC, mahdyar commented
Hello @emadPoursina,
First, you should claim the article in #1.
Also, read the `For New Translators` section there (#1):

> The pull request title should be same as the article, e.g. `An Introduction to JavaScript` (just like comment)

2021-03-28 07:47 UTC, mahdyar requested changes
Hello @emadPoursina,
First, you should claim the article in #1.
Also, read the `For New Translators` section there (#1):

> The pull request title should be same as the article, e.g. `An Introduction to JavaScript` (just like comment)

2021-03-28 10:21 UTC, emadPoursina commented
article has my name at issue comment and i change the pull request name to article i translated.

2021-03-28 11:23 UTC, mahdyar requested changes
There is a [folder](https://github.com/javascript-tutorial/fa.javascript.info/tree/master/1-js/02-first-steps/09-comparison/1-comparison-questions) which contains the tasks and solutions that should also be translated.

2021-03-28 11:23 UTC, mahdyar commented on 1-js/02-first-steps/09-comparison/article.md
> +ما عملگرهای زیادی را از ریاضی می شناسیم.
`عملگرهای مقایسه‌ای زیادی را از ریاضیات می‌شناسیم.` would be a better translation.

2021-03-28 11:23 UTC, mahdyar commented on 1-js/02-first-steps/09-comparison/article.md
> +یک علامت مقایسه برابری `==` یک مشکل دارد. این عملگر بین `0` و `false` تفاوتی قائل نمی شود:
`یک علامت مقایسه برابری معمولی`

2021-03-28 11:23 UTC, mahdyar commented on 1-js/02-first-steps/09-comparison/article.md
> +## برابری در رشته ها
It's strict, not strings.

2021-03-28 11:23 UTC, mahdyar commented on 1-js/02-first-steps/09-comparison/article.md
> +دقیقا همین اتفاق برای رشته خالی هم می افتد:
`یک رشتهٔ خالی`

2021-03-28 11:23 UTC, mahdyar commented on 1-js/02-first-steps/09-comparison/article.md
> +## جمع بندی
`خلاصه` is what we used in other articles, so it'd be better if you use the same.

2021-03-28 11:23 UTC, mahdyar commented on 1-js/02-first-steps/09-comparison/article.md
> +### از مشکلات دوری کن.
`اجتناب از مشکلات`

2021-03-28 11:23 UTC, mahdyar commented on 1-js/02-first-steps/09-comparison/article.md
> +حال بگذارید که چند اتفاق با مزه و جالب که زمانی که این قانون ها را اعمال می افتند را بررسی کنیم ; و مهم تر از همه ببینیم که چگونه داخل این تله ها نیافتیم.
`نیفتیم`

2021-03-28 11:23 UTC, mahdyar commented on 1-js/02-first-steps/09-comparison/article.md
> +حال بگذارید که چند اتفاق با مزه و جالب که زمانی که این قانون ها را اعمال می افتند را بررسی کنیم ; و مهم تر از همه ببینیم که چگونه داخل این تله ها نیافتیم.
`;` is not needed, use `.`.

2021-03-28 11:23 UTC, mahdyar commented on 1-js/02-first-steps/09-comparison/article.md
> +حال بگذارید که چند اتفاق با مزه و جالب که زمانی که این قانون ها را اعمال می افتند را بررسی کنیم ; و مهم تر از همه ببینیم که چگونه داخل این تله ها نیافتیم.
`زمانی که این قانون‌ها را اعمال می‌کنیم را ببینیم`

2021-03-28 11:23 UTC, mahdyar commented on 1-js/02-first-steps/09-comparison/article.md
> +حال بگذارید که چند اتفاق با مزه و جالب که زمانی که این قانون ها را اعمال می افتند را بررسی کنیم ; و مهم تر از همه ببینیم که چگونه داخل این تله ها نیافتیم.
Instead of
`چند اتفاق با مزه و جالب که زمانی که`,
`چند اتفاق با مزه و جالب زمانی که` would be a better translation.

2021-03-28 13:26 UTC, emadPoursina commented on 1-js/02-first-steps/09-comparison/article.md
> +حال بگذارید که چند اتفاق با مزه و جالب که زمانی که این قانون ها را اعمال می افتند را بررسی کنیم ; و مهم تر از همه ببینیم که چگونه داخل این تله ها نیافتیم.
`
حال بگذارید که چند اتفاق با مزه و جالب که زمانی که این قانون ها را اعمال می کنیم، می افتند را ببینیم.`

I think is better.

2021-03-28 13:28 UTC, emadPoursina commented on 1-js/02-first-steps/09-comparison/article.md
> +حال بگذارید که چند اتفاق با مزه و جالب که زمانی که این قانون ها را اعمال می افتند را بررسی کنیم ; و مهم تر از همه ببینیم که چگونه داخل این تله ها نیافتیم.
`چند اتفاق بامزه و جالب که با اعمال این قانون ها می افتند را ببینیم.‍`
 
I think is better.

2021-03-28 13:41 UTC, emadPoursina commented
/done

2021-03-28 15:13 UTC, mahdyar requested changes

2021-03-28 15:13 UTC, mahdyar commented on 1-js/02-first-steps/09-comparison/1-comparison-questions/solution.md
> +دلیل پاسخ ها:
`بعضی از دلایل:` would be a better translation.

2021-03-28 15:13 UTC, mahdyar commented on 1-js/02-first-steps/09-comparison/1-comparison-questions/task.md
> +اهمیت: 5
Metadata shouldn't be translated. [[+](https://github.com/javascript-tutorial/fa.javascript.info#metadata)]

2021-03-28 15:13 UTC, mahdyar commented on 1-js/02-first-steps/09-comparison/1-comparison-questions/solution.md
> +7. برابری سختگیرانه برای دو داده از دو نوع متفاوت
Please don't remove dots from the end of sentences. e.g:
`برابری سختگیرانه برای دو داده از دو نوع متفاوت` <- `برابری سختگیرانه برای دو داده از دو نوع متفاوت.`

2021-03-28 15:13 UTC, mahdyar commented on 1-js/02-first-steps/09-comparison/1-comparison-questions/solution.md
> +7. برابری سختگیرانه برای دو داده از دو نوع متفاوت
Also in Persian, we don't have `,`,  using `،` would be a better idea.

2021-03-30 03:19 UTC, emadPoursina commented
/done

2021-03-30 08:28 UTC, mahdyar approved these changes

2021-03-30 08:28 UTC, merged