BigInt
javascript-tutorial/fa.javascript.info pull request #120
Opened 2021-05-04 17:19 UTC by amirhshahbazi

Translated the BigInt page.

2021-05-04 18:51 UTC, mahdyar requested changes
You don't need to make a new pull request for any changes you make. you can add more commits by pushing to the `BigInt` branch on your fork.
In addition to that, please read the [`Translation Tips`](https://github.com/javascript-tutorial/fa.javascript.info#translation-tips):
> Please keep line breaks and paragraphs "as is": don't add new lines and don't remove existing ones. Makes it easy to merge future changes from the English version into the translation.

You've removed the newline on line 8, please add it back.

2021-05-04 19:18 UTC, amirhshahbazi commented
Thanks for the review, @mahdyar
/done

2021-05-04 19:34 UTC, mahdyar requested changes

2021-05-04 19:34 UTC, mahdyar commented on 1-js/99-js-misc/05-bigint/article.md
> +## عملیات ریاضی
`Math operators` means `عملگرهای ریاضی`, not `عملیات ریاضی`.

2021-05-04 19:34 UTC, mahdyar commented on 1-js/99-js-misc/05-bigint/article.md
> +در نظر داشته باشید: عملیات تقسیم 5/2 نتیجه را بدون قسمت اعشار و رند شده به سمت صفر، باز می گرداند. همه ی عملیات بر روی bigint ها، مقداری را از نوع bigint باز می گردانند.
Put `5/2` between backticks as it was.

2021-05-04 19:34 UTC, mahdyar commented on 1-js/99-js-misc/05-bigint/article.md
> +alert(1n + 2); // خطا: Cannot mix BigInt and other types
There is no need to translate `Error` here.

2021-05-04 19:34 UTC, mahdyar commented on 1-js/99-js-misc/05-bigint/article.md
> +می بایست آن ها ابتدا به صورت زیر، توسط `BigInt()` یا `Number()` تبدیل کرد:
You missed `if needed`.

2021-05-04 19:34 UTC, mahdyar commented on 1-js/99-js-misc/05-bigint/article.md
> +## عملگرهای مقایسه
`مقایسه‌ای` would be a better translation.

2021-05-04 19:34 UTC, mahdyar commented on 1-js/99-js-misc/05-bigint/article.md
> +باید ابتدا از `Number()` برای تبدیل یک bigint به نوع عددی استفاده کرد.
There is no `ابتدا` in the text, don't add your own words. Also, you missed `so`.
`پس باید از...`

2021-05-04 19:34 UTC, mahdyar commented on 1-js/99-js-misc/05-bigint/article.md
> +alert( 0n || 2 ); // 2 (0n برابر با false است)
`Considering` means `در نظر گرفتن`.

2021-05-05 21:09 UTC, amirhshahbazi commented
Thanks,
/done

2021-05-06 07:41 UTC, mahdyar approved these changes
Thank you, @amirhshahbazi!

2021-05-06 07:41 UTC, merged