Iterables
javascript-tutorial/fa.javascript.info pull request #133
Opened 2021-07-21 16:13 UTC by mahdiHashemi14

Please review and comment / commit if anything is wrong

2021-07-21 18:37 UTC, mahdyar requested changes

2021-07-21 18:37 UTC, mahdyar commented on 1-js/05-data-types/06-iterable/article.md
> +اینجا پیاده‌سازی کامل را برای `range` به همراه اظهارات داریم:
```suggestion
اینجا پیاده‌سازی کامل `range` را به همراه ملاحظات داریم:
```

2021-07-21 18:37 UTC, mahdyar commented on 1-js/05-data-types/06-iterable/article.md
> +// 1. ابتدا این متد صدا زده می‌شود for..of با استفاده از
```suggestion
// 1. در ابتدا این متد صدا زده می‌شود for..of با صدازدن
```

2021-07-21 18:37 UTC, mahdyar commented on 1-js/05-data-types/06-iterable/article.md
> +از لحاظ فنی اینجا هم کار مشابهی را انجام می‌دهد:
```suggestion
از لحاظ فنی این هم کار مشابهی را انجام می‌دهد:
```

2021-07-21 18:37 UTC, mahdyar commented on 1-js/05-data-types/06-iterable/article.md
> +...اما این کوتاه‌تر است.
```suggestion
...اما این روش کوتاه‌تر است.
```

2021-07-22 07:11 UTC, mahdiHashemi14 commented
Thank you, @mahdyar 
/done

2021-07-22 08:14 UTC, mahdyar approved these changes
LGTM!
Thank you, @mahdiHashemi14!

2021-07-22 08:14 UTC, merged