Map and Set
javascript-tutorial/fa.javascript.info pull request #135
Opened 2021-07-29 11:47 UTC by mahdiHashemi14

Please review and commit / comment if anything is wrong

2021-07-29 23:12 UTC, always-maap approved these changes

2021-07-30 07:55 UTC, mahdyar requested changes

2021-07-30 07:55 UTC, mahdyar commented on 1-js/05-data-types/07-map-set/02-filter-anagrams/solution.md
> +    // کلمه را به حروف آن تقسیم می‌کنیم، آنها را مرتب می‌کنیم و به یکدیگر پیوند می‌زنیم
```suggestion
    // کلمه را به حروف آن تقسیم می‌کنیم، آنها را مرتب می‌کنیم و به یکدیگر متصل می‌کنیم
```

2021-07-30 07:55 UTC, mahdyar commented on 1-js/05-data-types/07-map-set/02-filter-anagrams/solution.md
> +برای اینکه بهتر شود بیایید آن را به چند خط تقسیم کنیم:
```suggestion
برای اینکه بهتر شود بیایید آن را به چندین خط تقسیم کنیم:
```

2021-07-30 07:55 UTC, mahdyar commented on 1-js/05-data-types/07-map-set/02-filter-anagrams/task.md
> +[واروواژه‌ها](https://fa.wikipedia.org/wiki/واروواژه) کلمه‌هایی هستند که تعداد برابری از حروف یکسان دارند اما با ترتیبی متفاوت.
```suggestion
[واروواژه‌ها](https://fa.wikipedia.org/wiki/واروواژه) کلمه‌هایی هستند که تعداد برابری از حروف یکسان دارند، اما با ترتیبی متفاوت.
```

2021-07-30 07:55 UTC, mahdyar commented on 1-js/05-data-types/07-map-set/02-filter-anagrams/task.md
> +یک تابع `aclean(arr)` بنویسید که آرایه‌ای پاک شده از واروواژه‌ها را برمی‌گرداند.
```suggestion
یک تابع `aclean(arr)` بنویسید که آرایه‌ای تهی از واروواژه‌ها را برمی‌گرداند.
```

2021-07-30 07:55 UTC, mahdyar commented on 1-js/05-data-types/07-map-set/article.md
> +// در مقدارها حلقه بزن (میزان آنها)
```suggestion
// در مقدارها حلقه بزن (میزان آن‌ها)
```

2021-07-30 08:58 UTC, mahdiHashemi14 commented
Thank you, @mahdyar 
/done

2021-07-30 09:11 UTC, mahdyar approved these changes
Thank you, @mahdiHashemi14!

2021-07-30 09:12 UTC, merged