Function object, NFE
javascript-tutorial/fa.javascript.info pull request #156
Opened 2021-09-21 17:51 UTC by mahdiHashemi14

Please review and comment / commit if anything is wrong

2021-09-21 19:17 UTC, mahdyar requested changes

2021-09-21 19:17 UTC, mahdyar commented on 1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/task.md
> +برای دیدن مثالی کامل از نحوه استفاده، کد محیط ایزوله ببینید.
```suggestion
برای دیدن مثالی کامل از نحوه استفاده، کد جعبهٔ شنی(sandbox) را ببینید.
```

Refrence: https://fa.wikipedia.org/wiki/جعبه_شنی_(امنیت_رایانه)

2021-09-22 04:13 UTC, mahdiHashemi14 commented
Thank you @mahdyar 
/done

2021-09-22 07:59 UTC, mahdyar approved these changes
Thank you, @mahdiHashemi14!

2021-09-22 08:00 UTC, merged