Recursion and stack
javascript-tutorial/fa.javascript.info pull request #159
Opened 2021-10-04 12:51 UTC by mahdiHashemi14

Line **48** of **"output-single-linked-list"** solution and line **36** of **"output-single-linked-list-reverse"** solution need more attention
Please review and comment/commit if anything is wrong

2021-10-04 15:30 UTC, mahdyar requested changes

2021-10-04 15:30 UTC, mahdyar commented on 1-js/06-advanced-functions/01-recursion/04-output-single-linked-list/solution.md
> +درباره اسامی خوب متغیر حرف بزنیم، `list` اینجا خودش یک لیست است. اولین المان آن. و ممکن است همانطور بماند. این موضوع واضح و قابل اطمینان است.
```suggestion
صحبت دربارهٔ اسامی خوب برای متغیرها شد، `list` اینجا خودش یک لیست است. اولین المان آن. و بهتر است همان‌طور بماند. این‌طوری واضح و اتکاپذیر است.
```

2021-10-04 15:30 UTC, mahdyar commented on 1-js/06-advanced-functions/01-recursion/05-output-single-linked-list-reverse/solution.md
> -The loop variant is also a little bit more complicated then the direct output.
It's a typo, it should've been like this:
>  The loop variant is also a little bit more complicated *than* the direct output.

Made a PR: https://github.com/javascript-tutorial/en.javascript.info/pull/2731

2021-10-04 15:30 UTC, mahdyar commented on 1-js/06-advanced-functions/01-recursion/05-output-single-linked-list-reverse/solution.md
> +نوع حلقه کمی پیچیده‌تر است سپس به صورت مستقیم نمایش می‌دهیم.
```suggestion
روش حلقه کمی پیچیده‌تر از نمایش‌دادن به صورت مستقیم است.
```

2021-10-04 15:30 UTC, mahdyar commented on 1-js/06-advanced-functions/01-recursion/article.md
> +# بازگشت و استک
Haven't you translated the word "stack" to "پشته" in other articles? 🤔

2021-10-04 16:53 UTC, mahdiHashemi14 commented on 1-js/06-advanced-functions/01-recursion/article.md
> +# بازگشت و استک
Did I? To be honest,  I can't remember😅
I'll check it out and change "stack" translation if it's "پشته" in other articles

2021-10-04 17:00 UTC, mahdiHashemi14 commented on 1-js/06-advanced-functions/01-recursion/article.md
> +# بازگشت و استک
Yes, you're right. I translated it as "پشته". I'll change the article.

2021-10-04 17:10 UTC, mahdiHashemi14 commented
Thank you @mahdyar 
/done

2021-10-05 08:33 UTC, mahdyar approved these changes
Thank you, @mahdiHashemi14!

2021-10-05 08:33 UTC, merged