Arrow functions revisited
javascript-tutorial/fa.javascript.info pull request #166
Opened 2021-10-30 13:42 UTC by mahdiHashemi14

Please review and comment/commit if anything is wrong

2021-10-30 13:43 UTC, mahdiHashemi14 commented on 1-js/06-advanced-functions/12-arrow-functions/article.md
> +به دلیل اینکه آن‌ها برای قطعه‌های کوتاهی از کد در نظر گرفته شده‌اند که «زمینه» خودشان را ندارند و در زمینه کنونی کار می‌کنند. و آن‌ها واقعا در این مورد استفاده می‌درخشند.
This line needs attention

2021-10-30 15:42 UTC, mahdyar requested changes

2021-10-30 15:42 UTC, mahdyar commented on 1-js/06-advanced-functions/12-arrow-functions/article.md
> +به دلیل اینکه آن‌ها برای قطعه‌های کوتاهی از کد در نظر گرفته شده‌اند که «زمینه» خودشان را ندارند و در زمینه کنونی کار می‌کنند. و آن‌ها واقعا در این مورد استفاده می‌درخشند.
```suggestion
به دلیل اینکه آن‌ها برای قطعه‌های کوتاهی از کد در نظر گرفته شده‌اند که «موقعیت»(context) خودشان را ندارند و در موقعیت کنونی کار می‌کنند. و آن‌ها واقعا در این مورد استفاده کاربرد دارند.
```

2021-10-30 15:42 UTC, mahdyar commented on 1-js/06-advanced-functions/12-arrow-functions/article.md
> +# بازدید دوباره از تابع‌های کمانی
I guess "سرکشی" would be a better translation for visit. something like "سرکشی دوباره".

2021-10-30 17:36 UTC, mahdiHashemi14 commented on 1-js/06-advanced-functions/12-arrow-functions/article.md
> +به دلیل اینکه آن‌ها برای قطعه‌های کوتاهی از کد در نظر گرفته شده‌اند که «زمینه» خودشان را ندارند و در زمینه کنونی کار می‌کنند. و آن‌ها واقعا در این مورد استفاده می‌درخشند.
I translated "context" as "زمینه" in other articles. I think "موقعیت" is a good translation for "position" or "location" or something like this. I'll add the English term in parentheses.

2021-10-30 17:39 UTC, mahdiHashemi14 commented
Thank you @mahdyar 
/done

2021-10-31 09:35 UTC, mahdyar approved these changes
LGTM;
Thank you, @mahdiHashemi14!

2021-10-31 09:35 UTC, merged