Property flags and descriptors
javascript-tutorial/fa.javascript.info pull request #168
Opened 2021-11-06 12:49 UTC by mahdiHashemi14

Please review and comment/commit if anything is wrong

2021-11-06 12:50 UTC, mahdiHashemi14 commented on 1-js/07-object-properties/01-property-descriptors/article.md
> +در حالت غیر سخت‌گیرانه، زمانی که ویژگی‌های غیر قابل نوشتن را تغییر و یا کاری مشابه انجام می‌دهیم اروری ایجاد نمی‌شود. اما همچنان این کار انجام نمی‌شود. در حالت غیر سخت‌گیرانه، کارهای نقص‌کننده‌ی پرچم
Line 126 needs more attention

2021-11-06 12:50 UTC, mahdiHashemi14 commented on 1-js/07-object-properties/01-property-descriptors/article.md
> +```smart header="تنها تغییر ممکن روی صفت: writable true -> false"
This header (line 269) needs more attention

2021-11-06 12:51 UTC, mahdiHashemi14 commented on 1-js/07-object-properties/01-property-descriptors/article.md
> +این متد همراه با `Object.defineProperties` می‌تواند به عنوان راهی «آگاه از پرچم‌ها» برای کپی کردن یک شیء استفاده شود:
Line 305 needs more attention

2021-11-06 14:58 UTC, mahdyar commented on 1-js/07-object-properties/01-property-descriptors/article.md
> +در حالت غیر سخت‌گیرانه، زمانی که ویژگی‌های غیر قابل نوشتن را تغییر و یا کاری مشابه انجام می‌دهیم اروری ایجاد نمی‌شود. اما همچنان این کار انجام نمی‌شود. در حالت غیر سخت‌گیرانه، کارهای نقص‌کننده‌ی پرچم
```suggestion
در حالت غیر سخت‌گیرانه، زمانی که بر روی ویژگی‌های غیرقابل نوشتن می‌نویسیم، هیچ اروری رخ نمی‌دهد. اما همچنان این کار انجام نمی‌شود. در حالت غیر سخت‌گیرانه، کارهای نقص‌کننده‌ی پرچم بی سر و صدا نادیده گرفته می‌شوند.
```

2021-11-06 15:00 UTC, mahdyar commented on 1-js/07-object-properties/01-property-descriptors/article.md
> +این متد همراه با `Object.defineProperties` می‌تواند به عنوان راهی «آگاه از پرچم‌ها» برای کپی کردن یک شیء استفاده شود:
```suggestion
این متد همراه با `Object.defineProperties` می‌تواند به عنوان راهی «همراه با پرچم‌ها» برای کپی کردن یک شیء استفاده شود:
```

2021-11-06 15:01 UTC, mahdyar requested changes
Please apply the suggestions.

2021-11-06 17:23 UTC, mahdiHashemi14 commented
Thank you @mahdyar 
/done

2021-11-07 13:06 UTC, mahdyar approved these changes

2021-11-07 13:07 UTC, merged