F.prototype
javascript-tutorial/fa.javascript.info pull request #171
Opened 2021-11-17 14:54 UTC by Amirhossein-Veysi

2021-11-18 11:18 UTC, Amirhossein-Veysi commented
Hello @mahdyar  and thanks for review,
/done

2021-11-18 15:52 UTC, mahdyar requested changes

2021-11-18 15:52 UTC, mahdyar commented on 1-js/08-prototypes/02-function-prototype/1-changing-prototype/task.md
> +اهمیت: 5
You shouldn't translate Metadata. [Read more](https://github.com/javascript-tutorial/fa.javascript.info#metadata)

2021-11-18 16:30 UTC, Amirhossein-Veysi commented
/done

2021-11-19 19:23 UTC, mahdyar approved these changes

2021-11-19 19:23 UTC, mahdyar commented
Thank you, @Amirhossein-Veysi!

2021-11-19 19:24 UTC, merged