Prototypal inheritance
javascript-tutorial/fa.javascript.info pull request #172
Opened 2021-11-19 15:53 UTC by mahdiHashemi14

Please review and comment/commit of anything is wrong

2021-11-19 16:15 UTC, mahdiHashemi14 commented
I didn't know how to translate [line 169](https://github.com/javascript-tutorial/fa.javascript.info/blob/9243586de6000ad116e00751678545bc6551bd06/1-js/08-prototypes/01-prototype-inheritance/article.md?plain=1#L169). Best to take a look.

2021-11-19 19:26 UTC, mahdyar requested changes

2021-11-19 19:26 UTC, mahdyar commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
>  rabbit.walk(); // Rabbit! Bounce-bounce!
```suggestion
rabbit.walk(); // خرگوش! بپر-بپر!
```

2021-11-19 19:43 UTC, mahdiHashemi14 commented
Thank you @mahdyar 
/done

2021-11-20 09:11 UTC, mahdyar approved these changes
Thank you, @mahdiHashemi14!

2021-11-20 09:12 UTC, merged