Object to primitive conversion
javascript-tutorial/fa.javascript.info pull request #177
Opened 2021-11-25 11:23 UTC by mahdiHashemi14

Please review and comment/commit if anything is wrong

2021-11-25 11:24 UTC, mahdiHashemi14 commented on 1-js/04-object-basics/09-object-toprimitive/article.md
> +متدهای `toString` و `valueOf` از زمان‌های گذشته وجود دارند. آن‌ها سمبل نیستند (سمبل‌ها انقدر قدیمی نیستند) بلکه متدهای «معمولی» هستند که اسمی رشته‌ای دارد. آن‌ها راهی جایگزین که «سبک قدیمی» دارد را ب
Line 139 needs more attention.

2021-11-25 11:25 UTC, mahdiHashemi14 commented on 1-js/04-object-basics/09-object-toprimitive/article.md
> +alert(obj + 2); // تبدیل به مقدار اصلی، یک رشته => ادغام برگرداند، (2 + "2") 22
More attention, please!

2021-11-25 11:26 UTC, mahdiHashemi14 commented on 1-js/04-object-basics/09-object-toprimitive/article.md
> +همینطور برای عملیات ریاضی، جاوااسکریپت راهی برای باطل کردن آن‌ها با استفاده از متدها را فراهم نمی‌کند، پس پروژه‌های زندگی واقعی به ندرت از آن‌ها روی شیءها استفاده می‌کنند.
These two lines (275 and 277) need more attention, too.

2021-11-25 16:34 UTC, mahdyar commented on 1-js/04-object-basics/09-object-toprimitive/article.md
> +متدهای `toString` و `valueOf` از زمان‌های گذشته وجود دارند. آن‌ها سمبل نیستند (سمبل‌ها انقدر قدیمی نیستند) بلکه متدهای «معمولی» هستند که اسمی رشته‌ای دارد. آن‌ها راهی جایگزین که «سبک قدیمی» دارد را ب
```suggestion
متدهای `toString` و `valueOf` از زمان‌های گذشته وجود دارند. آن‌ها سمبل نیستند (سمبل‌ها انقدر قدیمی نیستند) بلکه متدهای «معمولی» هستند که اسمی رشته‌ای دارد. آن‌ها راهی جایگزین برای پیاده‌سازی تبدیل به «سبک قدیمی» را  فراهم می‌کنند.
```

2021-11-25 16:40 UTC, mahdyar commented on 1-js/04-object-basics/09-object-toprimitive/article.md
> +alert(obj + 2); // تبدیل به مقدار اصلی، یک رشته => ادغام برگرداند، (2 + "2") 22
```suggestion
alert(obj + 2); // تبدیل به مقدار اصلی یک رشته برگرداند => ادغام، (2 + "2") 22
```

2021-11-25 16:42 UTC, mahdyar approved these changes
Please review the suggestion(s).

2021-11-25 16:44 UTC, mahdyar requested changes
Please review the suggestion(s).

2021-11-25 17:45 UTC, mahdiHashemi14 commented
Thank you @mahdyar 
I also had a question: do you think "جزء" is a good translation for "hint"? For example in [line 35](https://github.com/javascript-tutorial/fa.javascript.info/blob/2a31b9f2d7c657562fbf560bb6a5355a690c41c6/1-js/04-object-basics/09-object-toprimitive/article.md?plain=1#L35).

/done

2021-11-26 11:38 UTC, mahdyar approved these changes
> Thank you @mahdyar 
I also have a question: do you think "جزء" is a good translation for "hint"? For example in [line 35](https://github.com/javascript-tutorial/fa.javascript.info/blob/2a31b9f2d7c657562fbf560bb6a5355a690c41c6/1-js/04-object-basics/09-object-toprimitive/article.md?plain=1#L35).
/done 

Yes, that LGTM.
Thank you, @mahdiHashemi14!

2021-11-26 11:39 UTC, merged