Class inheritance
javascript-tutorial/fa.javascript.info pull request #178
Opened 2021-12-04 14:37 UTC by mahdiHashemi14

Please review and comment/commit if anything is wrong.

2021-12-04 14:51 UTC, mahdiHashemi14 commented on 1-js/09-classes/02-class-inheritance/article.md
> +- **سازنده‌های درون کلاس‌های ارث‌بر باید `super(...)` را فراخوانی کنند و (!) قبل از استفاده از `this` این کار را انجام دهند.**
Needs more attention.

2021-12-04 14:52 UTC, mahdiHashemi14 commented on 1-js/09-classes/02-class-inheritance/article.md
> +در جاوااسکریپت، تفاوتی بین تابع سازنده یک کلاس ارث‌بر (به «سازنده مشتق شده» هم شناخته می‌شود) و بقیه تابع‌ها وجود دارد. سازنده مشتق شده یک ویژگی درونی خاص `[[ConstructorKind]]:"derived"` را دارد. این
Needs more attention.

2021-12-04 14:52 UTC, mahdiHashemi14 commented on 1-js/09-classes/02-class-inheritance/article.md
> +    // را فراخوانی کن (animal) مانند خرگوش بپر بپر کن و متد والد...
Needs more attention.

2021-12-04 14:52 UTC, mahdiHashemi14 commented on 1-js/09-classes/02-class-inheritance/article.md
> +سپس `super` از آن برای شناختن پروتوتایپ والد و متدهای آن استفاده می‌کند.
Needs more attention.

2021-12-04 14:53 UTC, mahdiHashemi14 commented on 1-js/09-classes/02-class-inheritance/article.md
> +- در خط `(*)`، متد `tree.sayHi` از `rabbit` کپی شد. شاید ما فقط می‌خواهیم از تکرار کد جلوگیری کنیم؟
Needs more attention (translation of "duplication")

2021-12-04 14:54 UTC, mahdiHashemi14 commented on 1-js/09-classes/02-class-inheritance/article.md
> +اما اگر ما متد خودمان را درون `Rabbit` مشخص کنیم، مثل `stop()`، در عوض این متد استفاده خواهد شد:
Needs more attention.

2021-12-04 14:54 UTC, mahdiHashemi14 commented on 1-js/09-classes/02-class-inheritance/article.md
> +مقدار `super` در تابع کمانی با مقدار آن در `stop()` یکسان است و همانطور که توقع می‌رود کار می‌کند. اگر ما یک تابع «معمولی» را اینجا مشخص کرده بودیم، ارور ایجاد می‌شد:
Needs more attention.

2021-12-06 10:07 UTC, mahdyar commented on 1-js/09-classes/02-class-inheritance/article.md
> +سپس `super` از آن برای شناختن پروتوتایپ والد و متدهای آن استفاده می‌کند.
```suggestion
سپس `super` از آن برای رفع‌کردن پروتوتایپ والد و متدهای آن استفاده می‌کند.
```

2021-12-06 10:08 UTC, mahdyar requested changes
Please review the suggestions.

2021-12-06 10:57 UTC, mahdiHashemi14 commented
Thank you @mahdyar 
/done

2021-12-07 09:18 UTC, mahdyar approved these changes
Thank you, @mahdiHashemi14!

2021-12-07 09:18 UTC, merged