Static properties and methods
javascript-tutorial/fa.javascript.info pull request #179
Opened 2021-12-11 08:58 UTC by mahdiHash

Please review and comment/commit if anything is wrong.

2021-12-11 08:59 UTC, mahdiHash commented on 1-js/09-classes/03-static-properties-methods/article.md
> +اینجا `Article.compare` در «بالای» مقاله‌ها (articles) قرار دارد، به عنوان واسطه‌ای برای مقایسه آن‌ها. این متدی از یک مقاله نیست، بلکه برای کل کلاس است.
This line needs more attention.

2021-12-11 18:40 UTC, mahdyar commented on 1-js/09-classes/03-static-properties-methods/article.md
> +اینجا `Article.compare` در «بالای» مقاله‌ها (articles) قرار دارد، به عنوان واسطه‌ای برای مقایسه آن‌ها. این متدی از یک مقاله نیست، بلکه برای کل کلاس است.
```suggestion
اینجا `Article.compare` در «بالای» مقاله‌ها (articles) قرار دارد، به عنوان روشی برای مقایسه آن‌ها. این متدی برای یک مقاله(article) نیست، بلکه برای کل کلاس است.
```

2021-12-11 18:40 UTC, mahdyar requested changes
Please review the suggestion(s).

2021-12-11 18:55 UTC, mahdiHash commented
Thank you @mahdyar 
/done

2021-12-12 16:31 UTC, mahdyar approved these changes
Thank you, @mahdiHash!

2021-12-12 16:32 UTC, merged