Private and protected properties and methods
javascript-tutorial/fa.javascript.info pull request #182
Opened 2021-12-20 09:31 UTC by mahdiHash

Please review and comment/commit if anything is wrong

2021-12-20 09:33 UTC, mahdiHash commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +یعنی یک کارِ «بایدی» در توسعه هر چیزی پیچیده‌تر از یک برنامه "hello world".
This line needs more attention.

2021-12-20 09:34 UTC, mahdiHash commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +اگر ما مثال قهوه‌ساز را ادامه دهیم -- چیزی که درون آن است: یک مجرای بخار، المنت حرارت و غیره -- رابط درونی است.
This line needs more attention.

2021-12-20 09:34 UTC, mahdiHash commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +این دقیقا برای قهوه‌ساز هم صدق می‌کند: توان (power) هیچ‌وقت تغییر نمی‌کند.
This line needs more attention.

2021-12-20 09:34 UTC, mahdiHash commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +    اگر شما توسعه‌دهنده چنین کلاسی باشید، این عالی است که بتوانید متدهای خصوصی را با خیال راحت تغییر نام دهید، پارامترهای آن‌ها را تغییر دهید و حتی حذف کنید، چون هیچ کد بیرونی به آن‌ها وابسته نیست.
This line needs more attention.

2021-12-20 09:35 UTC, mahdiHash commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +    برای کاربران، زمانی که نسخه‌ای جدید منتشر می‌شود، ممکن است از درون تعمیرات اساسی نیاز داشته باشد اما اگر رابط بیرونی یکسان باشد هنوز برای ارتقا دادن ساده است.
This line needs more attention.

2021-12-20 09:35 UTC, mahdiHash commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +در حال حاضر، فیلدهای خصوصی به خوبی در میان مرورگرها پشتیبانی نمی‌شوند اما می‌توان برای آن‌ها پلیفیل ساخت.
This line needs more attention.

2021-12-23 16:04 UTC, mahdyar commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +یعنی یک کارِ «بایدی» در توسعه هر چیزی پیچیده‌تر از یک برنامه "hello world".
```suggestion
یعنی یک کارِ «بایدی» در توسعه هر چیزی پیچیده‌تر از یک برنامه‌ی «hello world».
```

2021-12-23 16:06 UTC, mahdyar commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +اگر ما مثال قهوه‌ساز را ادامه دهیم -- چیزی که درون آن است: یک مجرای بخار، المنت حرارت و غیره -- رابط درونی است.
```suggestion
اگر ما مقایسه را با قهوه‌ساز ادامه دهیم -- چیزی که درون آن است: یک مجرای بخار، المنت حرارت و غیره -- رابط درونی است.
```

2021-12-23 16:10 UTC, mahdyar commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +    اگر شما توسعه‌دهنده چنین کلاسی باشید، این عالی است که بتوانید متدهای خصوصی را با خیال راحت تغییر نام دهید، پارامترهای آن‌ها را تغییر دهید و حتی حذف کنید، چون هیچ کد بیرونی به آن‌ها وابسته نیست.
```suggestion
    اگر شما توسعه‌دهنده چنین کلاسی باشید، این خوب است که بتوانید متدهای خصوصی را با خیال راحت تغییر نام دهید، پارامترهای آن‌ها را تغییر دهید و حتی حذف کنید، چون هیچ کد بیرونی به آن‌ها وابسته نیست.
```

2021-12-23 16:12 UTC, mahdyar commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +در حال حاضر، فیلدهای خصوصی به خوبی در میان مرورگرها پشتیبانی نمی‌شوند اما می‌توان برای آن‌ها پلیفیل ساخت.
```suggestion
در حال حاضر، فیلدهای خصوصی به خوبی در میان مرورگرها پشتیبانی نمی‌شوند اما می‌توان برای آن‌ها از پلیفیل‌ها استفاده کرد.
```

2021-12-23 16:12 UTC, mahdyar requested changes
Please review the requested changes.

2021-12-23 16:19 UTC, mahdiHash commented
Thank you @mahdyar 
/done

2021-12-24 17:16 UTC, mahdyar approved these changes
Thank you, @mahdiHash!

2021-12-24 17:16 UTC, merged