DOM tree
javascript-tutorial/fa.javascript.info pull request #188
Opened 2022-01-07 19:26 UTC by Beroozam

2022-01-07 20:40 UTC, mahdiHash commented
Hi @Beroozam.  
Please open a pull request when the translation is ready.  
Since the article and other files are not fully translated yet, I'll convert this PR to draft for now.  
You can set it to "ready for review" whenever you're done translating.  
Good luck!

2022-01-12 19:27 UTC, Beroozam commented
Thank you in advance for your guidance

2022-01-13 11:16 UTC, mahdiHash requested changes
Please review the suggestions.
You can add the suggestions to batch and create a commit just once ([docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes)).

2022-01-13 11:16 UTC, mahdiHash commented on 2-ui/1-document/02-dom-nodes/article.md
> +به این ترتیب می‌توان یک گره از Elements را از کنسول دریافت کرد.
```suggestion
به این ترتیب می‌توان یک گره از Elements را در کنسول دریافت کرد.
```

2022-01-13 11:16 UTC, mahdiHash commented on 2-ui/1-document/02-dom-nodes/article.md
> +این البته برای اهداف اشکال زدایی است. از فصل بعدی به DOM با استفاده از جاوا اسکریپت دسترسی پیدا می‌کنیم و آن را اصلاح می‌کنیم.
```suggestion
این البته برای اهداف رفع خطا است. از فصل بعدی با استفاده از جاوااسکریپت به DOM دسترسی پیدا می‌کنیم و آن را اصلاح می‌کنیم.
```

2022-01-13 11:16 UTC, mahdiHash commented on 2-ui/1-document/02-dom-nodes/article.md
> +یک سند HTML/XML در داخل مرورگر به عنوان درخت DOM نشان داده می‌شود.
```suggestion
یک سند HTML/XML داخل مرورگر به عنوان درخت DOM نشان داده می‌شود.
```

2022-01-13 11:16 UTC, mahdiHash commented on 2-ui/1-document/02-dom-nodes/article.md
> +- ... و غیره، همه چیز در HTML جایگاه خود را در DOM دارد، حتی نظرات.
```suggestion
- ... و غیره، همه چیز در HTML جایگاه خود را در DOM دارد، حتی یادداشت‌ها.
```

2022-01-13 11:16 UTC, mahdiHash commented on 2-ui/1-document/02-dom-nodes/article.md
> +ما می‌توانیم از ابزارهای توسعه دهنده برای DOM Inspect و اصلاح آن به صورت دستی استفاده کنیم.
```suggestion
ما می‌توانیم از ابزارهای توسعه دهنده برای بازرسی DOM و اصلاح آن به صورت دستی استفاده کنیم.
```

2022-01-13 11:16 UTC, mahdiHash commented on 2-ui/1-document/02-dom-nodes/article.md
> +گره‌های DOM دارای ویژگی‌ها و روش‌هایی هستند که به ما امکان می‌دهند بین آنها پیمایش کنیم، آنها را اصلاح کنیم، در صفحه حرکت کنیم و موارد دیگر. در فصل‌های بعدی به آنها خواهیم پرداخت.
```suggestion
گره‌های DOM دارای ویژگی‌ها و روش‌هایی هستند که به ما امکان می‌دهند بین آن‌ها پیمایش کنیم، آن‌ها را اصلاح کنیم، در صفحه حرکت کنیم و موارد دیگر. در فصل‌های بعدی به آن‌ها خواهیم پرداخت.
```

2022-01-13 13:19 UTC, Beroozam commented on 2-ui/1-document/02-dom-nodes/article.md
> +این البته برای اهداف اشکال زدایی است. از فصل بعدی به DOM با استفاده از جاوا اسکریپت دسترسی پیدا می‌کنیم و آن را اصلاح می‌کنیم.
I think اشکال زدایی is better but رفع خطا also good.  خطا is better for 'error' not for 'debug' @mahdiHash

2022-01-13 13:58 UTC, Beroozam commented on 2-ui/1-document/02-dom-nodes/article.md
> +ساختار DOM اینطور خواهد بود:
I'm sorry for adding a new line

2022-01-13 14:57 UTC, Beroozam commented on 2-ui/1-document/02-dom-nodes/article.md
> +- ... و غیره، همه چیز در HTML جایگاه خود را در DOM دارد، حتی نظرات.
maybe کامنت is better

2022-01-13 16:41 UTC, mahdyar commented on 2-ui/1-document/02-dom-nodes/article.md
> +به عنوان مثال، نظرات:
IMO the phrase "comment" itself is more comprehensible for Persian readers:
```suggestion
به عنوان مثال، کامنت‌ها:
```

Although for the integration of the translation, "یادداشت" can be used as well.

2022-01-14 08:37 UTC, mahdiHash commented on 2-ui/1-document/02-dom-nodes/article.md
> +4. (comments) -- <span dir="rtl">گاهی اوقات می‌توانیم اطلاعات را در آنجا قرار دهیم، نشان داده نمی‌شود، اما JS می‌تواند آن را از DOM بخواند.</span>
For the article, other than code sections, the text will be using RTL when it's ready to publish. You can see this in the [Arabic](https://ar.javascript.info/) JavaScript tutorial.

To translate comments of a code block, you can read [ترجمۀ کامنت‌ها در کد](https://github.com/javascript-tutorial/fa.javascript.info#%D8%AA%D8%B1%D8%AC%D9%85%DB%80-%DA%A9%D8%A7%D9%85%D9%86%D8%AA%D9%87%D8%A7-%D8%AF%D8%B1-%DA%A9%D8%AF) of README. The whole point is to invert the order of the words (if the comment contains English words after translation).

But some English expressions need to be wrapped inside HTML tags with LTR. Most of these expressions start with numbers or symbols. There is an expression in this article which starts with a number followed by English words and you've put that inside a `<span>` tag with LTR. I thought it's not needed but when I checked the Arabic tutorial, I changed my mind. 

Thank you for caring about readability of the contents!

2022-01-14 08:49 UTC, mahdiHash commented on 2-ui/1-document/02-dom-nodes/article.md
> +ساختار DOM اینطور خواهد بود:
No need to be sorry! It just happens :)

2022-01-14 08:51 UTC, mahdiHash commented on 2-ui/1-document/02-dom-nodes/article.md
> +- ... و غیره، همه چیز در HTML جایگاه خود را در DOM دارد، حتی نظرات.
Yeah, I think "کامنت" is better.
Please change other lines that have "comment" in them, too.

2022-01-14 14:12 UTC, Beroozam reviewed
Finish review

2022-01-14 14:12 UTC, Beroozam commented on 2-ui/1-document/02-dom-nodes/article.md
> +4. (comments) -- <span dir="rtl">گاهی اوقات می‌توانیم اطلاعات را در آنجا قرار دهیم، نشان داده نمی‌شود، اما JS می‌تواند آن را از DOM بخواند.</span>
```suggestion
1. `document` -- "DOM" نقطه‌ی ورود به
2. (گره‌های عنصر) -- بلوک‌های ساختار درختی , HTML تگ‌های 
3. حاوی متن -- (گره‌های متن)
4. (کامنت‌ها) -- بخواند DOM گاهی اوقات می‌توانیم اطلاعات را در آنجا قرار دهیم، نشان داده نمی‌شود، اما جاوااسکریپت می‌تواند آن را از
```

Thank you for your attention and that I use the recommended way for Persian sentences in README and use from span LTR for some of English expression. thank you very much

2022-01-14 21:13 UTC, mahdiHash approved these changes
Thanks for your contribution, @Beroozam.

2022-01-14 21:48 UTC, mahdyar approved these changes
LGTM!

2022-01-14 21:49 UTC, merged