Promise
javascript-tutorial/fa.javascript.info pull request #197
Opened 2022-02-16 03:40 UTC by Beroozam

2022-02-16 14:55 UTC, mahdiHash requested changes

2022-02-16 14:55 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/01-re-resolve/solution.md
> +خروجی هست: `1`.
```suggestion
خروجی: `1`.
```

2022-02-16 14:55 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/01-re-resolve/solution.md
> +فراخوان دوم برای `resolve` نادیده گرفته می‌شود، زیرا فقط اولین فراخوان `reject/resolve` در نظر گرفته می‌شود. فراخوان‌های بیشتر نادیده گرفته می‌شوند.
```suggestion
فراخوانی دوم برای `resolve` نادیده گرفته می‌شود، زیرا فقط اولین فراخوانی `reject/resolve` در نظر گرفته می‌شود. فراخوانی‌های بعدی نادیده گرفته می‌شوند.
```

2022-02-16 14:55 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/01-re-resolve/task.md
> +# آیا Re-resolve یک وعده(promise) است؟
```suggestion
# آیا یک Promise دوباره resolve می‌شود؟
```

2022-02-16 14:55 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/02-delay-promise/solution.md
> +لطفاً توجه داشته باشید که در این تمرین `resolve` بدون آرگومان فراخوانی می‌شود. ما هیچ مقداری را از `delay` بر نمی‌گردانیم، فقط از تاخیر اطمینان حاصل کنید.
```suggestion
لطفاً توجه داشته باشید که در این تمرین `resolve` بدون آرگومان فراخوانی می‌شود. ما هیچ مقداری را از `delay` بر نمی‌گردانیم، فقط از تاخیر اطمینان حاصل می‌کنیم.
```

2022-02-16 17:28 UTC, mahdyar commented
> Thanks for the translation @Beroozam. Before I submit a review for other files, I need to know the translation of "Promise". I think "Promise" doesn't need a translation and it's fine to write it as is. What do you think @mahdyar?

I agree. it should be as it was.

2022-02-16 17:58 UTC, Beroozam commented
I had no idea about this so I wanted you to help in this translation but what do you think about the sentences that start in Persian that we put the phrase پرامیس and other places from Promise.
@mahdiHash 
@mahdyar

2022-02-17 10:24 UTC, mahdiHash commented
> I had no idea about this so I wanted you to help in this translation but what do you think about the sentences that start in Persian that we put the phrase پرامیس and other places from Promise. @mahdiHash @mahdyar

If you don't know the meaning of a word/sentence and couldn't find it in the glossary, you can ask us in the [Translation Help](https://github.com/javascript-tutorial/fa.javascript.info/issues/185) issue.

2022-02-17 12:53 UTC, mahdiHash requested changes
Please review the suggestions. 
You can add the suggestions to a batch and create a commit just once ([docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes)).
For now, ignore the suggestions about translation of "settled" until we see what @mahdyar says.

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +فراخوانی `finally(f).` شبیه به `then(f, f).` است به این معنا که `f` همیشه زمانی که وعده(promise) تسویه(settled) می‌شود اجرا می‌شود: خواه حل‌وفصل(resolve) یا رد(reject) شود.
```suggestion
فراخوانی `finally(f).` شبیه به `then(f, f).` است به این معنا که `f` همیشه زمانی که Promise حل (settled) می‌شود اجرا می‌شود: خواه حل‌وفصل (resolve) یا رد (reject) شود.
```

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +  // زمانی اجرا می‌شود که وعده تسویه شود، مهم نیست موفقیت‌آمیز باشد یا نه
```suggestion
  // زمانی اجرا می‌شود که وعده حل شود، مهم نیست موفقیت‌آمیز باشد یا نه
```

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +    :منتقل می‌شود `then` به `finally` به عنوان مثال، در اینجا نتیجه از
Please rewrite this line as a normal text, too.

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +    :پاس داده می‌شود `catch` به `finally` و در اینجا یک خطایی در وعده وجود دارد که از
```suggestion
    :و در  اینجا یک خطا در Promise وجود دارد که از `finally` به `catch` پاس داده می‌شود
```

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +این بسیار راحت است، زیرا `finally` به معنای پردازش یک نتیجه وعده(promise) نیست. بنابراین از آن عبور می‌کند.
```suggestion
این بسیار راحت است، زیرا `finally` به معنای پردازش نتیجه Promise نیست. بنابراین از آن عبور می‌کند.
```

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +در فصل بعدی بیشتر در مورد زنجیره وعده(promise) و انتقال نتیجه بین کنترل‌کننده‌ها صحبت خواهیم کرد.
```suggestion
در فصل بعدی بیشتر در مورد زنجیره Promise و انتقال نتیجه بین کنترل‌کننده‌ها صحبت خواهیم کرد.
```

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +````smart header="ما می توانیم اجراکننده‌ها را به وعده‌های تسویه‌شده متصل کنیم"
```suggestion
````smart header="ما می توانیم اجراکننده‌ها را به Promiseهای حل شده متصل کنیم"
```

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +اگر وعده‌ای در حال تعلیق است، کنترل‌کننده‌ها `then/catch/finally.` منتظر آن هستند. در غیر این صورت، اگر وعده‌ای قبلاً تسویه شده باشد، آنها فقط اجرا می کنند:
```suggestion
اگر وعده‌ای در حالت انتظار است، کنترل‌کننده‌ها `then/catch/finally.` منتظر آن می‌مانند. در غیر این صورت، اگر وعده‌ای قبلاً حل شده باشد، آنها فقط اجرا می‌شوند:
```

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +توجه داشته باشید که این باعث می‌شود وعده‌ها قدرتمندتر از سناریوی واقعی "فهرست اشتراک" باشد. اگر خواننده قبلا آهنگ خود را منتشر کرده باشد و سپس شخصی در لیست اشتراک ثبت نام کند، احتمالاً آن آهنگ را دری
```suggestion
توجه داشته باشید که این باعث می‌شود Promiseها قدرتمندتر از سناریوی واقعی "فهرست اشتراک" باشد. اگر خواننده قبلا آهنگ خود را منتشر کرده باشد و سپس شخصی در لیست اشتراک ثبت نام کند، احتمالاً آن آهنگ را دریافت نخواهد کرد. اشتراک در دنیای واقعی باید قبل از رویداد انجام شود.
```

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +وعده‌ها انعطاف‌پذیرتر هستند. ما می توانیم هر زمان که بخواهیم کنترل‌کننده‌ها را اضافه کنیم: اگر نتیجه از قبل وجود داشته باشد، آنها فقط اجرا می‌شوند.
```suggestion
انعطاف Promiseها بیشتر است. ما می توانیم هر زمان که بخواهیم کنترل‌کننده‌ها را اضافه کنیم: اگر نتیجه از قبل وجود داشته باشد، آنها فقط اجرا می‌شوند.
```

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +در مرحله بعد، بیایید نمونه‌های عملی بیشتری را ببینیم که چگونه وعده‌ها می‌توانند به ما در نوشتن کد ناهمزمان کمک کنند.
```suggestion
در مرحله بعد، بیایید نمونه‌های عملی بیشتری را ببینیم که چگونه Promiseها می‌توانند به ما در نوشتن کد ناهمزمان کمک کنند.
```

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +در اینجا یک نوع مبتنی بر کال‌بک(callback) است، فقط برای یادآوری آن:
```suggestion
اینجا یک نوع مبتنی بر callback داریم، فقط برای یادآوری آن:
```

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +بیایید آن را با استفاده از Promises بازنویسی کنیم.
```suggestion
بیایید آن را با استفاده از Promiseها بازنویسی کنیم.
```

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +تابع جدید `loadScript` نیازی به کال‌بک نخواهد داشت. درعوض، یک شی Promise ایجاد و برمی‌گرداند که پس از اتمام بارگیری حل‌وفصل می‌شود. کد بیرونی می‌تواند با استفاده از `then.`، کنترل‌کننده‌ها (توابع اشت
```suggestion
تابع جدید `loadScript` نیازی به callback نخواهد داشت. درعوض، یک شی Promise ایجاد و برمی‌گرداند که پس از اتمام بارگیری حل‌وفصل می‌شود. کد بیرونی می‌تواند با استفاده از `then.`، کنترل‌کننده‌ها (توابع اشتراک) را به آن اضافه کند:
```

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +  script => alert(`${script.src} بارگذاری شده است!`),
```suggestion
  script => alert(`اسکریپت ${script.src} بارگذاری شده است!`),
```

This way, the string will be shown in RTL using `alert` function.

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +ما می‌توانیم بلافاصله چند مزیت را نسبت به الگوی مبتنی بر کال‌بک(callback) مشاهده کنیم:
```suggestion
ما می‌توانیم بلافاصله چند مزیت را نسبت به الگوی مبتنی بر callback مشاهده کنیم:
```

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +| می‌توانیم `.then` را در یک Promise هر چند بار که بخواهیم فراخوانی کنیم. هر بار، یک `طرفدار` جدید، یک تابع اشتراک جدید، به "لیست اشتراک" اضافه می‌کنیم. اطلاعات بیشتر در مورد این در فصل بعدی: [](info
```suggestion
| Promiseها به ما این امکان را می‌دهند که کارها را به ترتیب طبیعی انجام دهیم. ابتدا `(loadScript(script` را اجرا می‌کنیم و `.then` می‌نویسیم که با نتیجه چه کنیم. | هنگام فراخوانی `loadScript(script, callback)` باید یک تابع `callback` در اختیار داشته باشیم. به عبارت دیگر، *قبل* از فراخوانی `loadScript` باید بدانیم که با نتیجه چه کنیم. |
| می‌توانیم `.then` را در یک Promise هر چند بار که بخواهیم فراخوانی کنیم. هر بار، یک `طرفدار` جدید، یک تابع اشتراک جدید، به "لیست اشتراک" اضافه می‌کنیم. اطلاعات بیشتر در مورد این در فصل بعدی: [](info:promise-chaining). | فقط یک کال‌بک می‌تواند وجود داشته باشد. |
```

2022-02-17 12:53 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +بنابراین وعده‌ها جریان کد و انعطاف‌پذیری بهتری به ما می‌دهند. اما موارد بیشتری وجود دارد. آن را در فصل‌های بعدی خواهیم دید.
```suggestion
بنابراین Promiseها جریان کد و انعطاف‌پذیری بهتری به ما می‌دهند. اما موارد بیشتری وجود دارد. آن را در فصل‌های بعدی خواهیم دید.
```

2022-02-24 08:02 UTC, mahdiHash commented
Hi @Beroozam.
Are you still working on the changes?
I changed my mind about translation of "settled". I think the meaning you've chosen is fine.
You can add all the suggestions to a batch and submit a commit just once ([docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes)). You only need to separately change the lines which have to be rewritten.

2022-03-01 08:09 UTC, Beroozam reviewed
Please review

2022-03-01 08:09 UTC, Beroozam commented on 1-js/11-async/02-promise-basics/article.md
> +- `result` — .تغییر می‌کند `error` فراخوانی می شود به `reject(error)`  یا زمانی که `value` به `resolve(value)` سپس با فراخوانی ،`undefined` در ابتدا
```suggestion
- `state` — در ابتدا `"pending"` سپس با فراخوانی، `resolve` به `"fulfilled"` یا زمانی که `reject` فراخوانی می‌شود به `"rejected"` تغییر می‌کند.
- `result` — در ابتدا `undefined`، سپس با فراخوانی `resolve(value)` به `value` یا زمانی که `reject(error)` فراخوانی می شود به  `error` تغییر می‌کند.
```

2022-03-01 08:09 UTC, Beroozam commented on 1-js/11-async/02-promise-basics/article.md
> +.را فراخوانی کند. هر تغییر وضعیتی نهایی است `reject` یا یک `resolve` اجرا‌کننده باید فقط یک
```suggestion
اجرا‌کننده باید فقط یک `resolve` یا یک `reject` را فراخوانی کند. هر تغییر وضعیتی نهایی است.
```

2022-03-01 08:09 UTC, Beroozam commented on 1-js/11-async/02-promise-basics/article.md
> +:نادیده گرفته می‌شوند `reject` و `resolve` همه فراخوانی‌های دیگر از
```suggestion
همه فراخوانی‌های دیگر از `resolve` و `reject` نادیده گرفته می‌شوند:
```

2022-03-01 08:09 UTC, Beroozam commented on 1-js/11-async/02-promise-basics/article.md
> +promise.then(alert); // نشان می‌دهد "done!" بعد از 1 ثانیه
```suggestion
promise.then(alert); // بعد از 1 ثانیه «انجام شده!» را نشان می‌دهد
```

2022-03-01 08:09 UTC, Beroozam commented on 1-js/11-async/02-promise-basics/article.md
> +  // زمانی اجرا می‌شود که وعده تسویه شود، مهم نیست موفقیت‌آمیز باشد یا نه
```suggestion
  // زمانی اجرا می‌شود که promise تسویه شود، مهم نیست موفقیت‌آمیز باشد یا نه
```

2022-03-01 09:47 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +- `result` — .تغییر می‌کند `error` فراخوانی می شود به `reject(error)`  یا زمانی که `value` به `resolve(value)` سپس با فراخوانی ،`undefined` در ابتدا
> The first phrase is English. so How is this possible when the first phrase is English? `state` , `result`

Whenever the tutorial is ready for deployment, we will change the text direction to "Right to Left" so the articles could be readable.

You can see these two lines are shown correctly in [Arabic](https://ar.javascript.info/promise-basics) translation:
![2022-03-01_131650](https://user-images.githubusercontent.com/72219881/156145548-a1292c91-8bcb-42fb-b253-916fa11a7fd8.png)


For now, we will not change the sentences in any way unless it's needed. 

This line and other lines don't need that change.

2022-03-01 09:52 UTC, mahdiHash commented on 1-js/11-async/02-promise-basics/article.md
> +  // زمانی اجرا می‌شود که وعده تسویه شود، مهم نیست موفقیت‌آمیز باشد یا نه
```suggestion
// تسویه شود، مهم نیست موفقیت‌آمیز باشد یا نه promise زمانی اجرا می‌شود که
```

2022-03-02 17:26 UTC, mahdiHash commented
Hi, @Beroozam.
If the translation is ready, please tell us so we merge it :)

2022-03-02 20:36 UTC, Beroozam commented
Hi, @mahdiHash 
It's done and ready. merge it please .

2022-03-03 11:14 UTC, mahdiHash approved these changes

2022-03-03 11:52 UTC, mahdyar approved these changes

2022-03-03 11:52 UTC, merged