Promises chaining
javascript-tutorial/fa.javascript.info pull request #223
Opened 2022-09-01 18:26 UTC by mahdiHash

Please review and comment/commit if anything is wrong.

2022-09-01 18:26 UTC, mahdiHash commented on 1-js/11-async/03-promise-chaining/article.md
> +اگر بخواهیم دقیق باشیم، یک مدیریت‌کننده ممکن است دقیقا یک promise برنگرداند اما شیءای به اصطلاح "thenable" را برگرداند - یک شیء دلخواه که متد `.then` را دارد. با این شیء درست مانند یک promise رفتار م
This line needs more attention.

2022-09-01 18:27 UTC, mahdiHash commented on 1-js/11-async/03-promise-chaining/article.md
> +ایده این است که کتابخانه‌های شخص ثالث ممکن است شیءهای «سازگار با promise» خودشان را پیاده‌سازی کنند. این شیءها ممکن است مجموعه‌ای از متدهای خودشان را داشته باشند اما با promiseها نیز سازگار باشند چون
This line needs more attention.

2022-09-01 18:27 UTC, mahdiHash commented on 1-js/11-async/03-promise-chaining/article.md
> +به عنوان یک عادت خوب، یک عمل ناهنگام باید همیشه یک promise برگرداند. این باعث می‌شود که بتوان بعد از آن عملیاتی را برنامه‌ریزی کرد؛ حتی اگر نخواهیم زنجیره را الان گسترش دهیم، ممکن است بعدا به آن نیاز
This line needs more attention.

2022-09-02 20:35 UTC, mahdyar requested changes

2022-09-02 20:35 UTC, mahdyar commented on 1-js/11-async/03-promise-chaining/article.md
> +کد پایین یک درخواست به user.json می‌فرستد و متن آن را از سرور بارگیری می‌کند:
You removed backticks all over the file, it's just an example, please add them back:
```suggestion
کد پایین یک درخواست به `user.json` می‌فرستد و متن آن را از سرور بارگیری می‌کند:
```

2022-09-02 20:35 UTC, mahdyar commented on 1-js/11-async/03-promise-chaining/article.md
> +برای خواندن پاسخ کامل، ما باید متد response.text() را فراخوانی کنیم: این متد یک promise برمی‌گرداند که بعد از دانلود شدن کامل متن از سرور ریموت، همراه با متن به عنوان نتیجه resolve می‌شود.
here's another one.

2022-09-03 16:26 UTC, mahdiHash commented
Thanks for your review, @mahdyar.
/done

2022-09-03 16:33 UTC, mahdyar approved these changes
Thank you, @mahdiHash!

2022-09-03 16:33 UTC, merged