Character classes
javascript-tutorial/fa.javascript.info pull request #252
Opened 2023-01-19 22:18 UTC by EhsanShahbazii

/done

2023-01-19 22:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/fa.javascript.info?pullRequest=252) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/fa.javascript.info?pullRequest=252) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/fa.javascript.info?pullRequest=252) it.</sub>

2023-01-19 22:31 UTC, EhsanShahbazii commented
I apologize for my delay.

2023-01-20 08:17 UTC, mahdiHash requested changes
Please review the changes.
You can add the suggestions to a batch and submit a single commit ([docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes)).

You inserted an empty line 182, please remove it.

2023-01-20 08:17 UTC, mahdiHash commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +مطابقت (هر کلاس کاراکتر regexp دارای کاراکتر نتیجه مربوطه است):
```suggestion
عبارت دارای مطابقت (هر کلاس کاراکتر regexp دارای کاراکتر نتیجه مربوطه است):
```

2023-01-20 08:17 UTC, mahdiHash commented on 9-regular-expressions/02-regexp-character-classes/article.md
>  ````warn header="Pay attention to spaces"
```suggestion
````warn header="به فاصله ها توجه کنید"
```
Headers have to be translated.

2023-01-20 08:17 UTC, mahdiHash commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +// یا می توانیم از کلاس s\ استفاده کنیم:
```suggestion
// :استفاده کنیم \s یا می توانیم از کلاس
```
Please follow this [guide](https://github.com/javascript-tutorial/fa.javascript.info#%D8%AA%D8%B1%D8%AC%D9%85%DB%80-%DA%A9%D8%A7%D9%85%D9%86%D8%AA%D9%87%D8%A7-%D8%AF%D8%B1-%DA%A9%D8%AF) for translating comments.

2023-01-20 08:17 UTC, mahdiHash commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +به عبارت دیگر، در یک عبارت باقاعده، همه کاراکترها مهم هستند. فضاها نیز همین طور.
```suggestion
به عبارت دیگر، در یک عبارت باقاعده، همه کاراکترها مهم هستند. فاصله ها نیز همین طور.
```

2023-01-20 08:17 UTC, mahdiHash commented on 9-regular-expressions/02-regexp-character-classes/article.md
>  - `pattern:\S` -- all but `pattern:\s`.
```suggestion
- `pattern:\S` -- هر چیزی به جز `pattern:\s`.
```

2023-01-20 08:17 UTC, mahdiHash commented on 9-regular-expressions/02-regexp-character-classes/article.md
>  - `pattern:\W` -- all but `pattern:\w`.
```suggestion
- `pattern:\W` -- هر چیزی به جز `pattern:\w`.
```

2023-01-20 08:17 UTC, mahdiHash commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +- `pattern:.` -- هر کاراکتری اگر `regxp` با پرچم `'s'`، در غیر این صورت هر کاراکتری به جز خط جدید `n\`.
```suggestion
- `pattern:.` -- اگر با پرچم `'s'` همراه باشد هر کاراکتری مورد قبول است، در غیر این صورت هر کاراکتری به جز خط جدید `n\`.
```

2023-01-20 08:17 UTC, mahdiHash commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +رمزگذاری یونیکد، که توسط جاوا اسکریپت برای رشته ها استفاده می شود، ویژگی های بسیاری را برای کاراکترها فراهم می کند، مانند: حروف به کدام زبان تعلق دارد (اگر حرف باشد)، آیا علامت نقطه گذاری است و غیره.
```suggestion
رمزگذاری یونیکد، که توسط جاوااسکریپت برای رشته ها استفاده می شود، ویژگی های بسیاری را برای کاراکترها فراهم می کند، مانند: حروف به کدام زبان تعلق دارد (اگر حرف باشد)، آیا علامت نقطه گذاری است و غیره.
```

2023-01-20 08:17 UTC, mahdiHash commented
> I apologize for my delay.

No worries.

2023-01-20 08:25 UTC, EhsanShahbazii commented
/done

2023-01-20 13:41 UTC, mahdiHash commented
Thanks for your contribution, @EhsanShahbazii.

2023-01-21 15:40 UTC, merged