Update article.md
javascript-tutorial/fa.javascript.info pull request #256
Opened 2023-02-07 14:48 UTC by isArman

correcting some grammatical mistakes.

2023-02-07 14:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/fa.javascript.info?pullRequest=256) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/fa.javascript.info?pullRequest=256) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/fa.javascript.info?pullRequest=256) it.</sub>

2023-02-07 21:06 UTC, mahdiHash commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +1. مرجع‌ها نمی‌توانند درون حلقه قرار بگیرند. اگر ما تلاش کنیم که `__proto__` را درون یک حلقه مقداردهی کنیم، جاوااسکریپت ارور ایجاد می‌کند.
I don't think "حلقه" is a good translation here. Maybe "چرخه" is a better option?
Let's have @mahdyar's thought on this, too.

2023-02-08 22:14 UTC, mahdyar requested changes
Please try to choose an eloquent name for your PR too.

2023-02-08 22:14 UTC, mahdyar commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +1. مرجع‌ها نمی‌توانند درون حلقه قرار بگیرند. اگر ما تلاش کنیم که `__proto__` را درون یک حلقه مقداردهی کنیم، جاوااسکریپت ارور ایجاد می‌کند.
I agree.
Loops are another concept in programming languages and may mislead readers.
The original word here was "circle" and "چرخه" is an appropriate translation for it.
```suggestion
1. مرجع‌ها نمی‌توانند درون چرخه قرار بگیرند. اگر ما تلاش کنیم که `__proto__` را درون یک حلقه مقداردهی کنیم، جاوااسکریپت ارور ایجاد می‌کند.
```

2023-02-09 05:13 UTC, isArman commented
I agree. I think "چرخه" is better translation than "حلقه". 
Thank you.

2023-02-09 08:58 UTC, mahdiHash commented
@isArman, you don't have to close the PR.
Please reopen it and just commit the suggested changes. You can do this directly from "Files changed" tab below this PR's name.
Your username will be on the contributors list.

2023-02-12 21:38 UTC, mahdyar approved these changes
Thank you, @isArman!

2023-02-12 21:38 UTC, merged