Anchors: string start ^ and end $
javascript-tutorial/fa.javascript.info pull request #257
Opened 2023-02-14 11:11 UTC by EhsanShahbazii

/done

2023-02-14 11:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/fa.javascript.info?pullRequest=257) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/fa.javascript.info?pullRequest=257) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/fa.javascript.info?pullRequest=257) it.</sub>

2023-02-15 18:23 UTC, mahdiHash requested changes
Please review the changes.
There must be an empty line after line 8. Please pay a good attention to line syncing, I may have missed one or two.
You can add the suggestions to a batch and submit a single commit ([docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes)).

2023-02-15 18:23 UTC, mahdiHash commented on 9-regular-expressions/04-regexp-anchors/article.md
> +در این موارد خاص، می‌توانیم به جای آن از روش‌های رشته‌ای `startsWith/endsWith` استفاده کنیم. برای تست های پیچیده تر باید از عبارات منظم استفاده شود.
```suggestion
در این موارد خاص، می‌توانیم به جای آن از متدهای مختص به رشته‌ها به نام `startsWith/endsWith` استفاده کنیم. برای تست های پیچیده تر باید از عبارات منظم استفاده شود.
```
Try to improve the readability of the translation even if you need to insert additional words to it.

2023-02-15 18:23 UTC, mahdiHash commented on 9-regular-expressions/04-regexp-anchors/article.md
> +## تست برای یک مسابقه کامل
```suggestion
## آزمایش یک انطباق کامل
```

2023-02-15 18:23 UTC, mahdiHash commented on 9-regular-expressions/04-regexp-anchors/article.md
> +هر دو لنگر با هم `$...^:pattern` اغلب برای آزمایش اینکه آیا یک رشته کاملاً با الگو مطابقت دارد یا نه استفاده می شود. به عنوان مثال، برای بررسی اینکه آیا ورودی کاربر در قالب مناسب است یا خیر.
```suggestion
هر دو anchor یعنی `$...^:pattern` با هم اغلب برای آزمایش اینکه آیا یک رشته کاملاً با الگو مطابقت دارد یا نه استفاده می شود. به عنوان مثال، برای بررسی اینکه آیا ورودی کاربر در قالب مناسب است یا خیر.
```

2023-02-15 18:23 UTC, mahdiHash commented on 9-regular-expressions/04-regexp-anchors/article.md
> +در زبان عبارات معمولی `pattern:\d\d:\d\d` است:
```suggestion
در زبان عبارات با قاعده به صورت `pattern:\d\d:\d\d` است:

```

2023-02-15 18:23 UTC, mahdiHash commented on 9-regular-expressions/04-regexp-anchors/article.md
> +alert( regexp.test(badInput) ); // نادرست
```suggestion
alert( regexp.test(goodInput) ); // true
alert( regexp.test(badInput) ); // false
```

2023-02-15 18:23 UTC, mahdiHash commented on 9-regular-expressions/04-regexp-anchors/article.md
> +در اینجا تطبیق `pattern:\d\d:\d\d` باید دقیقاً بعد از ابتدای متن `^:pattern` شروع شود و انتهای `$:pattern` باید بلافاصله دنبال شود.
```suggestion
در اینجا تطبیق `pattern:\d\d:\d\d` باید دقیقاً بعد از ابتدای متن `^:pattern` شروع شود و انتهای `$:pattern` باید بلافاصله به دنبال آن بیاید.
```

2023-02-15 18:23 UTC, mahdiHash commented on 9-regular-expressions/04-regexp-anchors/article.md
> +کل رشته باید دقیقاً در این قالب باشد. اگر انحراف یا یک کاراکتر اضافی وجود داشته باشد، نتیجه `نادرست` است.
```suggestion
کل رشته باید دقیقاً در این قالب باشد. اگر انحراف یا یک کاراکتر اضافی وجود داشته باشد، نتیجه `false` است.
```

2023-02-15 18:23 UTC, mahdiHash commented on 9-regular-expressions/04-regexp-anchors/article.md
> +اگر پرچم `pattern:m` وجود داشته باشد، لنگرها رفتار متفاوتی دارند. آن را در مقاله بعدی خواهیم دید.
```suggestion
اگر پرچم `pattern:m` وجود داشته باشد، anchorها رفتار متفاوتی دارند. آن را در مقاله بعدی خواهیم دید.
```

2023-02-15 18:23 UTC, mahdiHash commented on 9-regular-expressions/04-regexp-anchors/article.md
> +لنگرهای `^:pattern` و `$:pattern` تست هستند. عرض آنها صفر است.
```suggestion
anchorهای `^:pattern` و `$:pattern` تست هستند. عرض آنها صفر است.
```

2023-02-15 18:23 UTC, mahdiHash commented on 9-regular-expressions/04-regexp-anchors/1-start-end/solution.md
> +این کار یک بار دیگر نشان می دهد که مجریان کاراکترها نیستند، بلکه آزمایش هستند.
```suggestion
این کار یک بار دیگر نشان می دهد که anchorها کاراکتر نیستند، بلکه آزمایش هستند.
```

2023-02-15 18:23 UTC, mahdiHash commented on 9-regular-expressions/04-regexp-anchors/1-start-end/solution.md
> +رشته `""` خالی است. موتور ابتدا با `^:pattern` (شروع ورودی) مطابقت دارد، بله وجود دارد، و بلافاصله با `$:pattern` انتهایی، آن هم اینجاست. بنابراین یک مسابقه وجود دارد.
```suggestion
رشته `""` خالی است. موتور ابتدا `^:pattern` (شروع ورودی) را تطبیق می‌دهد، بله تطابق دارد، و بلافاصله `$:pattern` انتهایی را، آن هم مطابقت دارد. بنابراین یک انطباق داریم.
```

2023-02-15 18:30 UTC, mahdiHash commented
As far as I've seen till now, the words "reference" and "match" can be the candidates of "being a tough one to translate" contest!

2023-02-15 19:02 UTC, mahdyar commented on 9-regular-expressions/04-regexp-anchors/article.md
> +# لنگرها: رشته شروع ^ و پایان $
> I think "anchor" is better not to be translated. @mahdyar, what's your opinion?

I agree.

2023-02-15 20:15 UTC, mahdiHash commented
Alright @EhsanShahbazii, please make the requested changes and comment "/done" when you are.

2023-02-16 11:53 UTC, EhsanShahbazii commented
/done

2023-02-16 15:04 UTC, mahdiHash approved these changes

2023-02-16 15:05 UTC, mahdiHash commented
Thanks for your contribution, @EhsanShahbazii.

2023-02-16 16:31 UTC, mahdyar approved these changes

2023-02-16 16:31 UTC, merged