Multiline mode of anchors ^ $, flag "m"
javascript-tutorial/fa.javascript.info pull request #259
Opened 2023-03-14 09:39 UTC by EhsanShahbazii

/done

2023-03-14 10:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/fa.javascript.info?pullRequest=259) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/fa.javascript.info?pullRequest=259) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/fa.javascript.info?pullRequest=259) it.</sub>

2023-03-14 20:57 UTC, mahdyar commented
Don't you think the word `پرچم` in Persian doesn't fit here? 🤔  Maybe flag itself would be a better option?
Let's have @mahdiHash's opinion on this as well.

2023-03-14 21:02 UTC, EhsanShahbazii commented
> Don't you think the word `پرچم` in Persian doesn't fit here? 🤔  Maybe flag itself would be a better option?
> Let's have @mahdiHash's opinion on this as well.

In the previous article that we translated, we used the word "پرچم".  Of course, in my opinion, it is better that the words flag and anchor are not translated.  But because we translated in the previous article, that's why I also translated.

2023-03-15 08:37 UTC, mahdiHash commented
Sorry for the delay. I was a little busy.

I also think "flag" is better. But it's translated to "پرچم" in other articles, so we need to revert it in another PR.

For now, please left "flag" as is, @EhsanShahbazii.

2023-03-15 08:58 UTC, mahdiHash requested changes

2023-03-15 08:58 UTC, mahdiHash commented on 9-regular-expressions/05-regexp-multiline-mode/article.md
> +# حالت چند خطی anchors ^ $، پرچم "m"
```suggestion
# حالت چند خطی anchors ^ $، flag "m"
```

2023-03-15 08:58 UTC, mahdiHash commented on 9-regular-expressions/05-regexp-multiline-mode/article.md
> +حالت چند خطی با پرچم `pattern:m` فعال می شود.
```suggestion
حالت چند خطی با flag `pattern:m` فعال می شود.
```

2023-03-15 08:58 UTC, mahdiHash commented on 9-regular-expressions/05-regexp-multiline-mode/article.md
> +بدون پرچم `pattern:m` تنها رقم اول مطابقت دارد:
```suggestion
بدون flag `pattern:m` تنها رقم اول مطابقت دارد:
```

2023-03-15 08:58 UTC, mahdiHash commented on 9-regular-expressions/05-regexp-multiline-mode/article.md
> +بدون پرچم `pattern:m` و `$:pattern` دلاری فقط با انتهای کل متن مطابقت دارد، بنابراین فقط آخرین رقم پیدا می‌ شود.
```suggestion
بدون flag `pattern:m` و `$:pattern` دلاری فقط با انتهای کل متن مطابقت دارد، بنابراین فقط آخرین رقم پیدا می‌ شود.
```

2023-03-15 08:58 UTC, mahdiHash commented on 9-regular-expressions/05-regexp-multiline-mode/article.md
> +## جستجو در انتهای خط $
```suggestion
## جستجو در انتهای خط $

```

2023-03-15 13:34 UTC, EhsanShahbazii commented
/done

2023-03-15 14:45 UTC, mahdiHash requested changes
Please review the new changes.

2023-03-15 14:45 UTC, mahdiHash commented on 9-regular-expressions/05-regexp-multiline-mode/article.md
> +"شروع یک خط" به طور رسمی به معنای "بلافاصله پس از شکست خط" است: "^:pattern" آزمایشی در حالت چند خطی در همه موقعیت هایی که قبل از یک کاراکتر خط جدید "n\" قرار دارند مطابقت دارد.
```suggestion
"شروع یک خط" به طور رسمی به معنای "بلافاصله پس از شکست خط" است: آزمایش "^:pattern" در حالت چند خطی با همه موقعیت هایی که بعد از یک کاراکترِ خط جدید `n\` قرار دارند مطابقت دارد.
```

2023-03-15 14:45 UTC, mahdiHash commented on 9-regular-expressions/05-regexp-multiline-mode/article.md
> +بدون flag `pattern:m` و `$:pattern` دلاری فقط با انتهای کل متن مطابقت دارد، بنابراین فقط آخرین رقم پیدا می‌ شود.
```suggestion
بدون flag `pattern:m` و `$:pattern` علامت دلار فقط با انتهای کل متن مطابقت دارد، بنابراین فقط آخرین رقم پیدا می‌ شود.
```

2023-03-15 14:45 UTC, mahdiHash commented on 9-regular-expressions/05-regexp-multiline-mode/article.md
> +"پایان یک خط" به طور رسمی به معنای "بلافاصله قبل از شکست خط" است: تست "$:pattern" در حالت چند خطی در همه موقعیت‌هایی که توسط یک کاراکتر خط جدید "n\" جایگزین می‌ شود، مطابقت دارد.
```suggestion
"پایان یک خط" به طور رسمی به معنای "بلافاصله قبل از شکست خط" است: تست "$:pattern" در حالت چند خطی با همه موقعیت‌هایی که قبل از یک کاراکتر خط جدید "n\" قرار دارند، مطابقت دارد.
```

2023-03-15 14:45 UTC, mahdiHash commented on 9-regular-expressions/05-regexp-multiline-mode/article.md
> +برای یافتن یک خط جدید، می‌ توانیم نه تنها از لنگرهای `^:pattern` و `$:pattern`، بلکه از کاراکتر خط جدید `n\` استفاده کنیم.
```suggestion
برای یافتن یک خط جدید، می‌ توانیم نه تنها از anchorهای `^:pattern` و `$:pattern`، بلکه از کاراکتر خط جدید `n\` استفاده کنیم.
```

2023-03-15 14:45 UTC, mahdiHash commented on 9-regular-expressions/05-regexp-multiline-mode/article.md
> +بنابراین، زمانی که به کاراکترهای خط جدید در نتیجه نیاز داشته باشیم، از `n\` در الگو استفاده می‌ شود، در حالی که از لنگرها برای یافتن چیزی در ابتدا/پایان یک خط استفاده می‌ شود.
```suggestion
بنابراین، زمانی که به کاراکترهای خط جدید در نتیجه نیاز داشته باشیم، از `n\` در الگو استفاده می‌ شود، در حالی که از anchorها برای یافتن چیزی در ابتدا/پایان یک خط استفاده می‌ شود.
```

2023-03-15 14:45 UTC, mahdiHash requested changes
Please review the new changes.

2023-03-15 17:10 UTC, EhsanShahbazii commented
/done

2023-03-15 17:29 UTC, mahdiHash commented
Thanks for your contribution, @EhsanShahbazii.

2023-03-15 17:29 UTC, mahdiHash approved these changes

2023-03-15 19:26 UTC, mahdyar approved these changes

2023-03-15 19:27 UTC, merged