Fetch
javascript-tutorial/fa.javascript.info pull request #264
Opened 2023-07-08 16:21 UTC by amirroox

2023-07-08 16:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/fa.javascript.info?pullRequest=264) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/fa.javascript.info?pullRequest=264) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/fa.javascript.info?pullRequest=264) it.</sub>

2023-07-11 05:53 UTC, mahdiHash requested changes
Please review the suggestions (pay attention to the ones that are needed to be applied to the whole article).
You can add the suggestions to a batch and create a commit just once ([docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes)).

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/article.md
> +# واکشی (Fetch)
```suggestion
# Fetch
```

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/article.md
> +جاوا اسکریپت میتواند در هنگام نیاز، درخواست‌های شبکه را به سرور ارسال کرده و اطلاعات جدید را دریافت کند.
```suggestion
جاوااسکریپت می‌تواند در هنگام نیاز، درخواست‌های شبکه را به سرور ارسال کرده و اطلاعات جدید را دریافت کند.
```

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/article.md
> +برای مثال ما میتوانیم برای موارد زیر از درخواست استفاده کنیم:
```suggestion
برای مثال ما می‌توانیم برای موارد زیر از درخواست شبکه استفاده کنیم:
```
لطفا یا از نیم فاصله استفاده کنین یا فاصله اضافه کنین. «میتوانیم»‌ درست نیست.
برای بقیه مقاله هم این تغییر رو اعمال کنین.

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/article.md
> +کلمه "AJAX" کوتاه شده (<b>A</b>synchronous <b>J</b>avaScript <b>A</b>nd <b>X</b>ML) میباشد و مربوط به درخواست های شبکه در جاوااسکرپیت است.به هر حال، ما نیازی به XML نداریم و این عبارت از تاریخچه AJAX
```suggestion
کلمه "AJAX" کوتاه شده (<b>A</b>synchronous <b>J</b>avaScript <b>A</b>nd <b>X</b>ML) میباشد و مربوط به درخواست های شبکه در جاوااسکرپیت است.به هر حال، ما نیازی به XML نداریم و این عبارت از تاریخچه AJAX باقی مانده است. شاید اسم آن را شنیده باشید.
```
لطفا جملات رو حین ترجمه حذف نکنین.

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/article.md
> +متد `fetch()` مدلی جدید و همه کاره است، بنابراین با این روش شروع میکنیم. متاسفانه این روش توسط مرورگرهای قدیمی پشتیبانی نمیشود (با استفاده از polyfilled پشتیبانی میشود) اما در بین مرورگر های جدیدتر پ
```suggestion
متد `fetch()` مدلی جدید و همه کاره است، بنابراین با این روش شروع میکنیم. متاسفانه این روش توسط مرورگرهای قدیمی پشتیبانی نمیشود (می‌تواند pollyfill شود) اما در بین مرورگر های جدیدتر پشتیبانی بسیار خوبی دارد.
```

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/article.md
> +**در ابتدا `promise` از طریق متود `fetch` برگردانده میشود، خروجی یک نمونه از کلاس داخلی [Response](https://fetch.spec.whatwg.org/#response-class) است که شامل اطلاعاتی مثل Header و غیره است.**
```suggestion
**در ابتدا `promise` از طریق `fetch` برگردانده میشود، خروجی یک نمونه از کلاس داخلی [Response](https://fetch.spec.whatwg.org/#response-class) است که شامل اطلاعاتی مثل Header و غیره است.**
```

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/article.md
> +در این مرحله میتوانیم وضعیت HTTP که از طریق Promise آماده،را بررسی کنیم تا ببینیم آیا موفقیت آمیز بوده یا خیر؛ تا به اینجا بدنه (body) دریافت نکردیم.
```suggestion
در این مرحله میتوانیم وضعیت HTTP که از طریق Promise آماده شده را بررسی کنیم تا ببینیم آیا موفقیت آمیز بوده یا خیر؛ تا به اینجا بدنه (body) دریافت نکردیم.
```

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/article.md
> +اگر `fetch` قادر به انجام درخواست نباشد Promise را رد میکند، مثلا اگر مشکلات شبکه وجود داشته باشد یا سایت مورد نظر در دسترس نباشد.توجه کنید که وضعیت‌های این چنینی خطاهای 404 یا 500 را ایجاد نمیکنند.
```suggestion
اگر `fetch` قادر به ارسال درخواست HTTP نباشد Promise را رد میکند، مثلا اگر مشکلات شبکه وجود داشته باشد یا سایت مورد نظر در دسترس نباشد. پاسخ‌های غیر معمول HTTP مانند خطاهای 500 یا 404 اروری ایجاد نمی‌کنند.
```

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/article.md
> +ما میتوانیم وضیعیت HTTP را در خصوصیات پاسخ (response properties) دریافتی مشاهده کنیم:
```suggestion
ما میتوانیم وضیعیت HTTP را در ویژگی‌های پاسخ (response properties) دریافتی مشاهده کنیم:
```

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/article.md
> +**در مرحله دوم برای دریافت بدنه پاسخ (response body)،باید از یک فراخوانی روش اضافی (additional method call) استفاده کنیم.**
```suggestion
**در مرحله دوم برای دریافت بدنه پاسخ (response body)، باید متدی دیگر را فراخوانی کنیم.**
```
کلمه method به«متد» ترجمه میشه.

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/article.md
> +کلاس `Response` چندین متود مختلف بر پایه promise دارد که میتوانیم بدنه پاسخ را به صورت فرمت‌های مختلف دریافت کنیم:
```suggestion
کلاس `Response` چندین متد مختلف بر پایه promise دارد که می‌توانیم بدنه پاسخ را به صورت فرمت‌های مختلف دریافت کنیم:
```
لطفا در همه جای متن به جای «متود» از «متد»‌ استفاده کنین.

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/article.md
> +// برای استفاده <img> ساخت تگ
```suggestion
// برای استفاده از آن <img> ساخت تگ
```

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/article.md
> +اما لیستی از [HTTP هدرهای ممنوعه](https://fetch.spec.whatwg.org/#forbidden-header-name) وجود دارد که ما نمیتوانیم از آنها استفاده کنیم:
```suggestion
اما لیستی از [هدرهای ممنوعه HTTP](https://fetch.spec.whatwg.org/#forbidden-header-name) وجود دارد که ما نمیتوانیم از آنها استفاده کنیم:
```

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/article.md
> +- `response.headers` -- شی مانند Map با هدر HTTP.
```suggestion
- `response.headers` -- شی‌ای مانند Map با هدرهای HTTP.
```

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/article.md
> +- `headers` -- یک شی با درخواستهای هدر (هر هدری مجاز نیست)
```suggestion‌
- `headers` -- یک شی با درخواست‌های هدر (هر هدری مجاز نیست)
```

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/01-fetch-users/solution.md
> +اگر از `await Promise.all(names.map(name => fetch(...)))` استفاده کنیم و `.json()` را برروی نتایج فراخوانی کنیم، آنگاه باید منتظر بماند تا به همه درخواست‌ها پاسخ دهند. با اضافه کردن `.json()` به صورت
```suggestion
اگر از `await Promise.all(names.map(name => fetch(...)))` استفاده کنیم و `.json()` را برروی نتایج فراخوانی کنیم، آنگاه باید منتظر بماند تا همه درخواست‌ها پاسخ دهند. با اضافه کردن `.json()` به صورت مستقیم به هر `fetch` اطمینان حاصل می‌کنیم که هر کدام آنها به صورت جداگانه شروع به خواندن داده‌ها به صورت JSON می‌کند و منتظر یکدیگر نمی‌ماند.
```

2023-07-11 05:53 UTC, mahdiHash commented on 5-network/01-fetch/01-fetch-users/solution.md
> +این مثال نشان‌دهنده این است که چگونه API ناهمزمانی Promise در سطح پایین همچنان می‌تواند مفید باشد حتی اگر بیشتر از `async/await` استفاده شود.
```suggestion
این مثال نشان‌دهنده این است که چگونه متدهای Promise در سطح پایین همچنان می‌تواند مفید باشد حتی اگر بیشتر از `async/await` استفاده شود.
```

2023-07-12 19:24 UTC, amirroox commented
/done

2023-07-12 21:17 UTC, mahdyar approved these changes
LGTM!

2023-07-12 21:17 UTC, merged