Unicode, String internals
javascript-tutorial/fa.javascript.info pull request #269
Opened 2023-07-12 21:09 UTC by mostafa-nematpour

translate `Unicode, String internals`

2023-07-12 21:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/fa.javascript.info?pullRequest=269) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/fa.javascript.info?pullRequest=269) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/fa.javascript.info?pullRequest=269) it.</sub>

2023-07-12 21:35 UTC, mahdyar requested changes

2023-07-12 21:35 UTC, mahdyar commented on 1-js/99-js-misc/06-unicode/article.md
> +# یونی‌کد، رشته های داخلی
```suggestion
# یونی‌کد، درون رشته‌ها
```

2023-07-12 21:35 UTC, mahdyar commented on 1-js/99-js-misc/06-unicode/article.md
> +این بخش به دنبال عمیق شدن در رشته‌ها است. این دانش برای شما مفید خواهد بود اگر قصد دارید با شکلک‌ها، کاراکترهای ریاضی نادر یا هیروگلیف‌ها یا سایر نمادهای نادر سر و کار داشته باشید.
```suggestion
این بخش به دنبال عمیق شدن در رشته‌ها است. این دانش برای شما مفید خواهد بود اگر قصد دارید با ایموجی‌ها، کاراکترهای ریاضی نادر یا هیروگلیف‌ها یا سایر نمادهای نادر سر و کار داشته باشید.
```

2023-07-12 21:58 UTC, mostafa-nematpour commented
/done

2023-07-13 05:32 UTC, mahdiHash requested changes
Please review the suggestions.
You can add the suggestions to a batch and create a commit just once ([docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes)).

2023-07-13 05:32 UTC, mahdiHash commented on 1-js/99-js-misc/06-unicode/article.md
> +    این 256 کاراکتر اول شامل الفبای لاتین ، کاراکتر های نحوی ابتدایی و برخی چیزهای دیگر می‌شود. به عنوان مثال `"‎\x7A"` مانند نوشتن `"z"` هست. (یونی‌کد `U+007A`)
```suggestion
    این 256 کاراکتر اول شامل الفبای لاتین ، کاراکتر های نحوی ابتدایی و برخی چیزهای دیگر می‌شود. به عنوان مثال `"‎\x7A"` مانند نوشتن `"z"` هست. (یونی‌کد `U+007A`)
```
Please don't add an empty line.

2023-07-13 05:32 UTC, mahdiHash commented on 1-js/99-js-misc/06-unicode/article.md
> +    به جای `XXXX` باید 4 عدد هگزادسیمال در بازه `0000` و `FFFF` قرار گیرد. در نتیجه `‎\uXXXX` کاراکتری است که یونی‌کد آن `XXXX` هست.
```suggestion
 
    به جای `XXXX` باید 4 عدد هگزادسیمال در بازه `0000` و `FFFF` قرار گیرد. در نتیجه `‎\uXXXX` کاراکتری است که یونی‌کد آن `XXXX` هست.
```

2023-07-13 05:32 UTC, mahdiHash commented on 1-js/99-js-misc/06-unicode/article.md
> +تمامی کاراکترهای متداول دارای کدهای 2 بایتی هستند (4 رقم هگز). حروف در بیشتر زبان های اروپایی ، اعداد و مجموعه های ایدئوگرافیک چینی، ژاپنی و کره‌ای (CJK) ، با 2 بایت نمایش داده می‌شوند.
```suggestion
## جفت جایگزین (Surrogate pairs)

تمامی کاراکترهای متداول دارای کدهای 2 بایتی هستند (4 رقم هگز). حروف در بیشتر زبان های اروپایی ، اعداد و مجموعه های ایدئوگرافیک چینی، ژاپنی و کره‌ای (CJK) ، با 2 بایت نمایش داده می‌شوند.
```
Please don't remove any line.

2023-07-13 05:32 UTC, mahdiHash commented on 1-js/99-js-misc/06-unicode/article.md
> +// را می‌دهد 𝒳 به جفت‌ جایگزین آگاه نیست برای همین فقط کد قسمت اول charCodeAt
```suggestion
// را می‌دهد 𝒳 به جفت‌ جایگزین آگاه نیست برای همین فقط کد قسمت اول charCodeAt 

```

2023-07-13 05:32 UTC, mahdiHash commented on 1-js/99-js-misc/06-unicode/article.md
> +اکثر کاراکتر های رایج ترکیبات خود را هم در جدول یونی‌کد دارند. ولی نه همه آنها، زیرا تعداد ترکیبات ممکن بسیار زیاد خواهد شد.
```suggestion
به عنوان مثال حرف پایه می‌تواند `a` باشد و نمونه های مقابل را درست کرد: `àáâäãåā`. در زبان فارسی هم نمونه‌هایی و جود دارد مانند تشدید در `ملّت` و حروف صدادار.

اکثر کاراکتر های رایج ترکیبات خود را هم در جدول یونی‌کد دارند. ولی نه همه آنها، زیرا تعداد ترکیبات ممکن بسیار زیاد خواهد شد.
```

2023-07-13 06:34 UTC, mostafa-nematpour commented
Thanks for the suggestions Mehdi
I will try to be better and next time I will put all in one
I'm not good at it
/done

2023-07-13 10:44 UTC, mahdiHash commented
> Thanks for the suggestions Mehdi I will try to be better and next time I will put all in one I'm not good at it /done

No worries, mate :)
Thanks for your contribution, @mostafa-nematpour.

2023-07-13 10:44 UTC, mahdiHash approved these changes

2023-07-14 08:44 UTC, merged