Generators
javascript-tutorial/fa.javascript.info pull request #270
Opened 2023-07-13 11:32 UTC by alivarastepour

translation of article, task and solution is added.

2023-07-14 10:44 UTC, mahdiHash commented
سلام وقت بخیر.
بابت مشارکت و کمک شما ممنونم.
لطفا همه خط‌هایی که اضافه کردین رو حذف کنین.
تعداد خط‌های تمام فایل‌ها باید با تعداد خط‌ها قبل از ترجمه یکی باشه.
هر وقت انجام دادین لطفا <span dir="ltr">/done</span> رو کامنت کنین.

2023-07-15 07:32 UTC, mahdiHash requested changes
Please review the suggestions.
Change the translation of "object" to  «شیء» anywhere else needed.
You can add the suggestions to a batch and create a commit just once ([docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes)).

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/01-pseudo-random-generator/task.md
> +برای این منظور "seeded pseudo-random generators" استفاده می‌شوند. این generatorها یک "seed" -مقدار اولیه- را می‌گیرند و طبق یک فرمول باقی دنباله را تولید می‌کنند. در نتیجه "seed" یکسان دنباله یکسانی
```suggestion
برای این منظور "seeded pseudo-random generators" (generatorهای شبه تصادفی با یک هسته اولیه) استفاده می‌شوند. این generatorها یک "seed" -مقدار اولیه- را می‌گیرند و طبق یک فرمول باقی دنباله را تولید می‌کنند. در نتیجه "seed" یکسان دنباله یکسانی را تولید می‌کند و کل دنباله را به راحتی می‌توان بازتولید کرد. فقط نیاز است "seed" را به یاد داشته باشیم.
```

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/01-pseudo-random-generator/task.md
> +تسک، ساختن یک تابع generator با امضای `pseudoRandom(seed)` است که یک "seed" می‌گیرد و یک generator با فرمول داده شده می‌سازد.
```suggestion
تسک، ساختن یک تابع generator با نام `pseudoRandom(seed)` است که یک "seed" می‌گیرد و یک generator با فرمول داده شده می‌سازد.
```
امضا درسته. ولی بیاین ساده‌تر بنویسیم :)

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +توابع معمول فقط یک‌بار می‌توانند یک مقدار(مثلا یک object یا undefined) را برگردانند.
```suggestion
توابع معمولی فقط یک‌بار می‌توانند یک مقدار(مثلا یک object یا undefined) را برگردانند.
```

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +اما generatorها می‌توانند چندین بار، بر اساس تقاضا، مقادیر متفاوت را برگردانند(اصطلاحا yield کنند.). generatorها با [iterableها](info:iterable) به خوبی کار می‌کنند و به کمک آن‌ها می‌توان جریان‌های دا
```suggestion
اما generatorها می‌توانند چندین بار، بر اساس تقاضا، مقادیر متفاوت را برگردانند(اصطلاحا yield کنند.). generatorها با [حلقه‌پذیرها](info:iterable) (iterable) به خوبی کار می‌کنند و به کمک آن‌ها می‌توان جریان‌های داده ساخت.
```

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +توابع generator با توابع معمول، رفتار متفاوتی دارند. زمانی که این توابع صدا می‌شوند، بدنه آن‌ها اجرا نمی‌شود؛ در عوض، یک آبجکت خاص به نام "generator object" برمی‌گردانند که به وسیله آن اجرای تابع را
```suggestion
توابع generator با توابع معمولی، رفتار متفاوتی دارند. زمانی که این توابع صدا می‌شوند، بدنه آن‌ها اجرا نمی‌شود؛ در عوض، یک شیء خاص به نام "generator object" برمی‌گردانند که به وسیله آن اجرای تابع را می‌توان کنترل کرد.
```

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +//برمی‌گرداند generator یک آبجکت generator تابع
```suggestion
//برمی‌گرداند generator یک شیء generator تابع
```

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +\*/!*
لطفا دلیل اضافه کردن این دوتا رو بگین.

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +متد اصلی یک آبجکت generator متد `()next` است. هنگامی که صدا می‌شود، بدنه تابع تا اولین `yield value` اجرا می‌شود(`value` می‌تواند حذف شود که در این صورت `undefined` است.)؛ سپس اجرای تابع متوقف می‌شود
```suggestion
متد اصلی یک شیء generator متد `()next` است. هنگامی که صدا می‌شود، بدنه تابع تا اولین `yield value` اجرا می‌شود(`value` می‌تواند حذف شود که در این صورت `undefined` است.)؛ سپس اجرای تابع متوقف می‌شود و مقدار yield شده برگرداننده می‌شود.
```
لطفا "object" رو به «شیء» ترجمه کنین :)

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +برای مثال، در کد زیر، یک آبجکت generator ایجاد شده و اولین مقدار `yield` شده توسط آن گرفته شده است:
```suggestion
برای مثال، در کد زیر، یک شیء generator ایجاد شده و اولین مقدار `yield` شده توسط آن گرفته شده است:
```

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +دیگر صدا کردن `()generator.next` منطقی نیست. اگر این کار را انجام دهیم، آبجکت یکسانی با `done:true` برگردانده می‌شود.
```suggestion
دیگر صدا کردن `()generator.next` منطقی نیست. اگر این کار را انجام دهیم، شیء یکسانی با `done:true` برگردانده می‌شود.
```

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +## generatorها iterable هستند.
```suggestion
## generatorها حلقه‌پذیر هستند.
```

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +همان‌طور که احتمالا با توجه به `()next` متوجه شده‌اید، generatorها [iterable](info:iterable) هستند.
```suggestion
همان‌طور که احتمالا با توجه به `()next` متوجه شده‌اید، generatorها [حلقه‌پذیر](info:iterable) هستند.
```

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +علت این اتفاق این است که `for..of` آخرین مقدار را هنگامی که `done:true` است در نظر نمی‌گیرد. هنگام برگرداندن آخرین مقدار با `return`، بر خلاف `done:true`، `yield` است. در نتیجه برای نشان دادن تمام مق
```suggestion
علت این اتفاق این است که `for..of` آخرین مقدار را هنگامی که `done:true` است در نظر نمی‌گیرد. آخرین مقدار برگردانده شده با `return`، بر خلاف `yield`، حاوی `done:true` است. در نتیجه برای نشان دادن تمام مقادیر در حلقه `for..of` باید آن‌ها را با `yield` برگردانیم:
```

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +از آنجایی که generatorها iterable هستند، از تمام functionality آن‌ها نیز برای generatorها می‌توان استفاده کرد؛ مثل spread syntax `...`:
```suggestion
از آنجایی که generatorها حلقه‌پذیر هستند، از تمام functionality آن‌ها نیز برای generatorها می‌توان استفاده کرد؛ مثل spread syntax `...`:
```

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +در کد بالا، `()generateSequence...`، باعث می‌شود آبجکت generator که iterable هم هست به آرایه‌ای از اعداد تبدیل شود.(درباره spread syntax در چپتر [](info:rest-parameters-spread#spread-syntax) بیشتر بخ
```suggestion
در کد بالا، `()generateSequence...`، باعث می‌شود شیء generator که حلقه‌پذیر هم هست به آرایه‌ای از اعداد تبدیل شود.(درباره spread syntax در فصل [](info:rest-parameters-spread#spread-syntax) بیشتر بخوانید.)
```

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +## استفاده از generatorها برای iterableها
```suggestion
## استفاده از generatorها برای حلقه‌پذیرها
```

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +تا الان، generatorها بسیار شبیه به آبجکت‌های iterable با یک سینتکس خاص برای تولید مقادیر بودند؛ درواقع اما generatorها بسیار قدرتمندتر و انعطاف پذیرتر هستند.
```suggestion
تا الان، generatorها بسیار شبیه به شیءهای حلقه‌پذیر با یک سینتکس خاص برای تولید مقادیر بودند؛ درواقع اما generatorها بسیار قدرتمندتر و انعطاف پذیرتر هستند.
```

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +برای این کار باید `()generator.next` را با یک argument صدا کنیم. این argument تبدیل به مقدار برگردانده شده توسط خود yield درون generator می‌شود.
```suggestion
برای این کار باید `()generator.next` را با یک آرگومان صدا کنیم. این argument تبدیل به مقدار برگردانده شده توسط خود yield درون generator می‌شود.
```

2023-07-15 07:32 UTC, mahdiHash commented on 1-js/12-generators-iterators/1-generators/article.md
> +در جاوااسکریپت مدرن، generatorها کم استفاده می‌شوند. اما گاهی اوقات می‌توانند مفید باشند؛ رد و بدل کردن داده با کد صدا زننده، یک قابلیت منحصر بفرد است. هم‌چنین برای ساخت iterableها هم بکار می‌روند.
```suggestion
در جاوااسکریپت مدرن، generatorها کم استفاده می‌شوند. اما گاهی اوقات می‌توانند مفید باشند؛ رد و بدل کردن داده با کد صدا زننده، یک قابلیت منحصر بفرد است. هم‌چنین برای ساخت حلقه‌پذیرها هم بکار می‌روند.
```

2023-07-15 07:59 UTC, alivarastepour commented
/done

2023-07-15 08:15 UTC, mahdiHash commented
Thanks for your contribution, @alivarastepour :D

2023-07-15 08:15 UTC, mahdiHash approved these changes

2023-07-15 12:23 UTC, mahdyar approved these changes

2023-07-15 12:23 UTC, merged