Focusing: focus/blur
javascript-tutorial/fa.javascript.info pull request #282
Opened 2023-08-11 12:55 UTC by shahrzadJavadiKoushesh

/done

2023-08-11 19:08 UTC, mahdiHash requested changes
سلام @shahrzadJavadiKoushesh.
بابت مشارکت شما ممنونم.
لطفا به برابر بودن خط‌های اضافه و حذف شده بین مقاله اصلی و مقاله ترجمه شده توجه کنین. این دو مورد باید برابر باشن.
این مشکل رو برطرف کنین و بعدش <span dir="ltr">/done</span> رو کامنت کنین.

2023-08-13 17:49 UTC, shahrzadJavadiKoushesh commented
/done

2023-08-14 09:30 UTC, mahdiHash requested changes
لطفا کامنت‌ها رو نگاه بندازین و به تغییراتی که باید روی کل مقاله اعمال بشن هم توجه کنین.
می‌تونین تمام suggestionها رو داخل یه دسته قرار بدین و با هم کامیت کنین ([docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes))

2023-08-14 09:30 UTC, mahdiHash commented on 2-ui/4-forms-controls/2-focus-blur/article.md
>  ```warn header="JavaScript-initiated focus loss"
```suggestion
```warn header="از دست دادن focus ایجاد شده توسط جاوااسکریپت"
```

2023-08-14 09:30 UTC, mahdiHash commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +:هم می‌تواند باعث آن شود. برای مثال javascript می‌کند اما خود click یکی از آن‌ها وقتی است که بازدیدکننده روی جای دیگری
```suggestion
یکی از آن‌ها وقتی است که بازدیدکننده روی جای دیگری کلیک می‌کند. اما خود جاوااسکریپت هم می‌تواند باعث آن شود. برای مثال:
```
این خط‌ها کد نیستن پس لطفا مثل متن معمولی ترجمه کنین.
لطفا ترجمه خط‌ها پایینی هم درست کنین.

2023-08-14 09:30 UTC, mahdiHash commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +توسط کاربر را ردیابی کنیم، خودمان باید از ایجاد آن اجتناب کنیم. focus-loss مراقب باشید. اگر می‌خواهیم events بهترین دستورالعمل این است که موقع کار با این
```suggestion
بهترین دستورالعمل این است که موقع کار با این eventها مراقب باشید. اگر بخواهیم از دست دادن focus که توسط کاربر انجام می‌شود را ردیابی کنیم، پس باید از ایجاد آن توسط خودمان جلوگیری کنیم.
```

2023-08-14 09:30 UTC, mahdiHash commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +## اجازه focus کردن روی هر عنصری را می‌دهد: tabindex
```suggestion
## اجازه focus کردن روی هر عنصر: tabindex
```

2023-08-14 09:30 UTC, mahdiHash commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +ما می‌توانیم `tabindex` از JavaScript را با استفاده از `elem.tabIndex` اضافه کنیم. آن هم اثر یکسان را دارد
```suggestion
ما می‌توانیم `tabindex` از جاوااسکریپت را با استفاده از `elem.tabIndex` اضافه کنیم. آن هم اثر یکسان را دارد
```

2023-08-14 09:30 UTC, mahdiHash commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +کنیم، مثل این highlight بگذاریم تا آن را `<form>` را روی `onfocus` برای مثال ما نمی‌توانیم
این دو خط هم باید مثل متن معمولی ترجمه بشن.
لطفا ترتیب کلمه‌ها رو درست کنین.

2023-08-14 09:30 UTC, mahdiHash commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +.وجود ندارد `blur` و `focus` رفتار بالا رفتن حبابی در
```suggestion
.وجود ندارد `blur` و `focus` رفتار بالا رفتن به صورت حبابی در
```

2023-08-14 09:30 UTC, mahdiHash commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +مثال بالا کار نمی‌کند زیرا وقتی کاربر روی یک `<input>` فوکوس می‌کند، `focus` event فقط روی آن input فعال می‌شود. رفتار بالا رفتن حبابی ندارد. پس `form.onfocus` هیچوقت فعال نمی‌شود.
```suggestion
مثال بالا کار نمی‌کند زیرا وقتی کاربر روی یک `<input>` فوکوس می‌کند، `focus` event فقط روی آن input فعال می‌شود. رفتار بالا رفتن به صورت حبابی را ندارد. پس `form.onfocus` هیچوقت فعال نمی‌شود.
```

2023-08-14 09:30 UTC, mahdiHash commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +ابندا یک ویژگی قدیمی خنده‌دار وجود دارد: `focus/blur` بالا رفتن حبابی ندارند، بلکه در مرحله‌ی capturing به پایین منتشر می‌شوند.
```suggestion
ابتدا یک ویژگی قدیمی خنده‌دار وجود دارد: `focus/blur` رفتار بالا رفتن به صورت حبابی را ندارند، بلکه در مرحله‌ی capturing به پایین منتشر می‌شوند.
```

2023-08-14 09:30 UTC, mahdiHash commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +پس در اینجا یک نوع کار دیگر هست:
```suggestion
پس در اینجا یک نوع دیگر داریم که کار می‌کند:
```

2023-08-14 15:03 UTC, shahrzadJavadiKoushesh commented
/done

2023-08-16 07:12 UTC, mahdiHash requested changes
لطفا مشکل خط‌های ۱۰۰ تا ۱۰۳ و خط ۱۷۶ هم برطرف کنین.

2023-08-16 07:12 UTC, mahdiHash commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +.شوند trigger بدرفتاری کنند -- زمانی که نیاز نیست `focus/blurs` این ویژگی‌ها گاهی باعث می‌شوند -
خط‌های ۱۰۰ تا ۱۰۳ مثل کامنت ترجمه شدن. لطفا ترجمه این خط‌ها رو مثل متن اصلی انجام بدین.

2023-08-16 12:25 UTC, shahrzadJavadiKoushesh commented
/done

2023-08-16 14:08 UTC, mahdiHash commented
مرسی از همراهی‌تون @shahrzadJavadiKoushesh :)

2023-08-16 14:10 UTC, mahdiHash approved these changes

2023-08-16 14:10 UTC, merged

2023-08-16 14:22 UTC, shahrzadJavadiKoushesh commented
ممنون از کمک‌های شما