Patch3
javascript-tutorial/fa.javascript.info pull request #283
Opened 2023-08-12 07:18 UTC by HannaParsa

2023-08-12 10:05 UTC, HannaParsa commented
/done

2023-08-16 07:21 UTC, mahdiHash requested changes
سلام @HannaParsa.
لطفا به یکسان بودن تعداد خط‌های مقاله ترجمه شده و مقاله اصلی توجه کنین. این مورد رو برطرف کنین.
همچنین شما داخل این PR مقاله [regexp-unicode](https://github.com/javascript-tutorial/fa.javascript.info/pull/283/files#diff-2ae4b44e98cc4945c5e4ec6a729874113398e71fe0ed81be108a8005bd26bcd0) هم تغییر دادید. برای هر PR فقط یه مقاله باید ترجمه بشه. لطفا تغییرات این فایل رو برگردونین.
بعد از انجام این کارها <span dir="ltr">/done</span> رو کامنت کنین.
مرسی که به ترجمه کمک می‌کنین.

2023-08-16 08:32 UTC, HannaParsa commented
/done

2023-08-17 10:47 UTC, mahdiHash requested changes
لطفا به پیشنهادها نگاه بندازین. به مواردی که باید روی کل مقاله اعمال بشن توجه کنین (تغییر معنی کلمه‌ها).
می‌تونین suggestionها رو داخل یه دسته قرار بدین و یه کامیت ثبت کنین ([docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request)).

2023-08-17 10:47 UTC, mahdiHash commented on 2-ui/2-events/05-dispatch-events/article.md
> +راهی برای تشخیص یک user event "واقعی" از event تولید شده توسط اسکریپت وجود دارد.
```suggestion
```smart header="event.isTrusted"
راهی برای تشخیص یک user event "واقعی" از event تولید شده توسط اسکریپت وجود دارد.
```
این خط‌ها رو حذف نکنین چون جزوی از مقاله هستن.

2023-08-17 10:47 UTC, mahdiHash commented on 2-ui/2-events/05-dispatch-events/article.md
> +ویژگی 'event.isTrusted' برای رویدادهایی که از اقدامات واقعی کاربر ناشی می شوند 'true' و برای رویدادهای تولید شده توسط اسکریپت 'false' است.
```suggestion
ویژگی 'event.isTrusted' برای رویدادهایی که از اقدامات کاربر واقعی ناشی می شوند 'true' و برای رویدادهای تولید شده توسط اسکریپت 'false' است.
```
بعد از این خط <code>```</code> رو اضافه کنین.

2023-08-17 10:47 UTC, mahdiHash commented on 2-ui/2-events/05-dispatch-events/article.md
>  ## Bubbling example
```suggestion
## مثالی از Bubbling
```

2023-08-17 10:47 UTC, mahdiHash commented on 2-ui/2-events/05-dispatch-events/article.md
> +1. باید از `addEventListener` برای custom  کردن  event  ها استفاده کرد، زیرا `on<event>` فقط برای built-in event وجود دارد و `document.onhello` کار نمیکند.
```suggestion
1. باید از `addEventListener` برای شخصی‌سازی eventها استفاده کرد، زیرا `on<event>` فقط برای eventهای متعلق به زبان وجود دارد و `document.onhello` کار نمی کند. 
```

2023-08-17 10:47 UTC, mahdiHash commented on 2-ui/2-events/05-dispatch-events/article.md
> +2. باید `bubbles:true` را  set  کنیم مگرنه event  bubble up  نخواهد شد.
```suggestion
2. باید `bubbles:true` را تنظیم کنیم وگرنه رویداد bubble up نخواهد شد.
```

2023-08-17 10:47 UTC, mahdiHash commented on 2-ui/2-events/05-dispatch-events/article.md
> +مکانیک bubbling برای built-in (`click`) و custom (`hello`) یکسان است.  هم چنین مراحلی برای گرفتن و bubbling نیز وجود دارد.
```suggestion
مکانیک bubbling برای event درون‌ساخت (`click`) و event شخصی‌سازه‌شده (`hello`) یکسان است.  هم چنین مراحلی برای capturing و bubbling نیز وجود دارد.
```

2023-08-17 10:47 UTC, mahdiHash commented on 2-ui/2-events/05-dispatch-events/article.md
>  ## Custom events
```suggestion
## eventهای شخصی‌سازی‌شده
```
«سفارشی»‌ هم برای معنی custom می‌تونه استفاده بشه.

2023-08-17 10:47 UTC, mahdiHash commented on 2-ui/2-events/05-dispatch-events/article.md
> +برای انواع events های کاملاً جدید خودمان مانند  `"hello"` باید از "CustomEvent جدید" استفاده کنیم. از نظر فنی [CustomEvent](https://dom.spec.whatwg.org/#customevent) با «رویداد» یکسان است،البته با یک
```suggestion
برای انواع events های کاملاً جدید خودمان مانند  `"hello"` باید از `new CustomEvent` استفاده کنیم. از نظر فنی [CustomEvent](https://dom.spec.whatwg.org/#customevent) با `Event` یکسان است،البته با یک استثنا.
```
کلمات CustomEvent و Event مربوط به کلاس‌های موجود در زبان هستن. این موارد نباید ترجمه بشن. کلمه new هم به همین علت نباید ترجمه بشه.
لطفا backtickها (<code>``</code>) رو به کوتیشن (<code>" "</code>) تبدیل نکنین.

2023-08-17 10:47 UTC, mahdiHash commented on 2-ui/2-events/05-dispatch-events/article.md
> +ویژگی "detail" می تواند هر داده ای را داشته باشد. از نظر فنی می‌توانیم بدون آن زندگی کنیم، زیرا می‌توانیم هر ویژگی را پس از ایجاد یک شی `new Event` معمولی به آن اختصاص دهیم. اما `CustomEvent` فیلد  `
```suggestion
ویژگی `detail` می تواند هر داده ای را داشته باشد. از نظر فنی می‌توانیم آن را تنظیم نکنیم، زیرا می‌توانیم هر ویژگی را پس از ایجاد یک شی `new Event` معمولی به آن اختصاص دهیم. اما `CustomEvent` فیلد  `detail` ویژه ای را برای جلوگیری از conflicts با سایر property های event فراهم می کند.
```

2023-08-17 10:47 UTC, mahdiHash commented on 2-ui/2-events/05-dispatch-events/article.md
> +علاوه بر این، event class توضیح می‌دهد که «چه نوع رویدادی» است، و اگر event is custom است، باید از  `CustomEvent` استفاده کنیم تا مشخص شود که چیست.
```suggestion
علاوه بر این، کلاس event توضیح می‌دهد که «چه نوع رویدادی» است، و اگر event سفارشی باشد، باید از  `CustomEvent` استفاده کنیم تا مشخص شود که چیست.
```

2023-08-17 10:47 UTC, mahdiHash commented on 2-ui/2-events/05-dispatch-events/article.md
> +نکته: event  حتما باید  flag `cancelable: true` را داشته باشد یا اینکه `event.preventDefault()` فراخوانی نمیشود.
```suggestion
نکته: event  حتما باید `cancelable: true` را داشته باشد یا اینکه `event.preventDefault()` فراخوانی نمی شود. 
```

2023-08-17 10:47 UTC, mahdiHash commented on 2-ui/2-events/05-dispatch-events/article.md
> +بدون اینکه برای `onclick` handler صبر کند تا تمام شود، شروع به process شدن میشود:
```suggestion
بدون اینکه برای هندلر `onclick` صبر کند تا تمام شود، پردازش می‌ شود:   
```

2023-08-17 10:47 UTC, mahdiHash commented on 2-ui/2-events/05-dispatch-events/article.md
> +سپس می‌توانیم `dispatchEvent` (یا یک تماس event-triggering) را در انتهای `onclick` قرار دهیم یا، شاید بهتر، آن را در `setTimeout` با تاخیر صفر قرار دهیم:
```suggestion
سپس می‌توانیم `dispatchEvent` (یا یک فراخوانی event-triggering) را در انتهای `onclick` قرار دهیم یا، شاید بهتر، آن را در `setTimeout` با تاخیر صفر قرار دهیم:
```

2023-08-17 10:47 UTC, mahdiHash commented on 2-ui/2-events/05-dispatch-events/article.md
>  ## Summary
```suggestion
## خلاصه
```

2023-08-20 04:29 UTC, HannaParsa commented on 2-ui/2-events/05-dispatch-events/article.md
> +- به صورت پیش فرض: `{bubbles: false, cancelable: false}`.
سلام برای این مورد راستش چیزی به ذهنم نرسید

2023-08-20 04:29 UTC, HannaParsa commented
/done

2023-08-20 04:32 UTC, HannaParsa commented
/done

2023-08-20 06:28 UTC, mahdiHash commented on 2-ui/2-events/05-dispatch-events/article.md
> +- به صورت پیش فرض: `{bubbles: false, cancelable: false}`.
ایرادی نداره. اگه موقع ترجمه به کمک احتیاج داشتین می‌تونین داخل ایشو #185 سوالتون رو بپرسین.

2023-08-20 06:42 UTC, mahdiHash approved these changes
ممنون از همراهی‌تون @HannaParsa :)

2023-08-20 06:42 UTC, merged

2023-08-20 07:14 UTC, HannaParsa commented
خواهش می کنم :)