Shadow Dom
javascript-tutorial/fa.javascript.info pull request #317
Opened 2024-01-16 12:19 UTC by alas1n

2024-01-16 12:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/fa.javascript.info?pullRequest=317) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/fa.javascript.info?pullRequest=317) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/fa.javascript.info?pullRequest=317) it.</sub>

2024-01-18 17:34 UTC, mahdyar requested changes
سلام، مرسی از مشارکتتون.
لطف کنید قبل از بررسی کامل، خودتون ترجمه رو بررسی کنید و یک ترجمه روون و مطابق با راهنمای ترجمه (readme و ایشو) بدید. همچنین می‌تونید PRهای قبلی رو مشاهده کنید و مطابق اونا انجام بدید.

تعداد خط‌ها هم بررسی کنید و ترجمهٔ هر خط باید دقیقا داخل همون خط باشه.

مرسی.

2024-01-25 11:15 UTC, alas1n commented
@mahdyar 

با تشکر feedback 
ترجمه خط به خط اضافه شد

2024-01-25 11:16 UTC, alas1n commented
@mahdyar 

با تشکر feedback 
ترجمه خط به خط اضافه شد 

/done

2024-01-27 09:12 UTC, mahdyar requested changes

2024-01-27 09:12 UTC, mahdyar commented on 8-web-components/3-shadow-dom/article.md
>  </style>
Please don't use formatters, remove the extra spaces.

2024-01-29 17:15 UTC, alas1n commented
فرمتر اصلاح شد 
/done

2024-01-30 09:16 UTC, mahdyar reviewed
Please also replace سایه with shadow anywhere you used it. It shouldn't get translated.

2024-01-30 09:17 UTC, mahdyar requested changes
Please also replace سایه with shadow anywhere you used it. It shouldn't get translated.

2024-01-31 11:37 UTC, alas1n commented
سایه به shadow 
روشن به light 
درخت به tree
بازگردانی شد 

/done

2024-02-01 17:40 UTC, mahdyar approved these changes
Thank you, @alas1n!

2024-02-01 17:41 UTC, merged