Destructuring assignment
javascript-tutorial/fa.javascript.info pull request #86
Opened 2021-01-02 17:12 UTC by Arash-1999

2021-01-04 05:50 UTC, kooshan75 commented on 1-js/05-data-types/10-destructuring-assignment/1-destruct-user/task.md
> +یک تخصیص ساختارشکنانه بنویسید که این شرایطرا داشته باشد:
Please put a whitespace between "شرایط" and "را".

2021-01-04 05:51 UTC, kooshan75 commented on 1-js/05-data-types/10-destructuring-assignment/article.md
> +اما زمانیکه ما آنها ره به یک تابع میدهیم٬ ممکن است یک شی یا آرایه را بطور کامل نخواهد٬ بلکه قسمت های جداگانه ای را بخواهد.
Change "ره" to "را"

2021-01-04 05:53 UTC, kooshan75 commented on 1-js/05-data-types/10-destructuring-assignment/article.md
> -alert(surname);  // Kantor
You don't need to change sample written code :)

2021-01-04 05:54 UTC, kooshan75 commented on 1-js/05-data-types/10-destructuring-assignment/article.md
> -````smart header="\"Destructuring\" does not mean \"destructive\"."
Also, this shouldn't be deleted as well.

2021-01-04 05:54 UTC, kooshan75 commented on 1-js/05-data-types/10-destructuring-assignment/article.md
> -// let [firstName, surname] = arr;
no need to delete the whitespace :)

2021-01-04 05:55 UTC, kooshan75 commented on 1-js/05-data-types/10-destructuring-assignment/article.md
> -````
Don't delete the original backtick count.

2021-01-04 05:55 UTC, kooshan75 commented on 1-js/05-data-types/10-destructuring-assignment/article.md
> -````smart header="Ignore elements using commas"
You've also deleted this.

2021-01-04 05:56 UTC, kooshan75 commented on 1-js/05-data-types/10-destructuring-assignment/article.md
> -let [firstName, , title] = ["Julius", "Caesar", "Consul", "of the Roman Republic"];
Was this autocomplete? You don't need to change original sample code.

2021-01-04 05:56 UTC, kooshan75 commented on 1-js/05-data-types/10-destructuring-assignment/article.md
> -alert( title ); // Consul
Keep the original code.

2021-01-04 05:57 UTC, kooshan75 commented on 1-js/05-data-types/10-destructuring-assignment/article.md
> -In the code above, the second element of the array is skipped, the third one is assigned to `title`, and the rest of the array items is also skipped (as there are no variables for them).
I think you've forgotten translating this.

2021-01-04 05:57 UTC, kooshan75 commented on 1-js/05-data-types/10-destructuring-assignment/article.md
> -````smart header="Works with any iterable on the right-side"
Translation needed.

2021-01-04 05:58 UTC, kooshan75 commented on 1-js/05-data-types/10-destructuring-assignment/article.md
> -let [a, b, c] = "abc"; // ["a", "b", "c"]
Keep the original code please.

2021-01-04 05:59 UTC, kooshan75 requested changes
There was too many changes in the original code that you need to redo and then resubmit again. Thanks for the contribution.

2021-01-07 17:38 UTC, Arash-1999 commented
/done

2021-01-09 00:09 UTC, kooshan75 requested changes
I think you didn't read my comments on your translation carefully. please read and fix them. Thanks.

2021-01-12 18:05 UTC, Arash-1999 commented
\done

2021-01-13 18:32 UTC, mehradsadeghi commented
Dear @kooshan75 please `resolve` each comment that is being fixed by @Arash-1999.

2021-01-23 12:20 UTC, kooshan75 commented
Dear @Arash-1999 I reviewed your translation but there were too many code changes and conflicts that has made it too hard for me to even review the changes that have been made. I humbly ask to keep the original code and replace the translation parts only. I will close this PR and please submit another PR with resolved conflicts and code changes. Best of luck.

2021-01-23 12:20 UTC, closed without merging