Constructor, operator "new"
javascript-tutorial/fa.javascript.info pull request #98
Opened 2021-03-19 19:19 UTC by mahdiHashemi14

Please review and commit if anything is wrong.
All the files in "Constructor, operator new" are translated.

2021-03-19 19:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/fa.javascript.info?pullRequest=98) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/fa.javascript.info?pullRequest=98) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/fa.javascript.info?pullRequest=98) it.</sub>

2021-03-19 20:31 UTC, mahdyar requested changes

2021-03-19 20:31 UTC, mahdyar commented on 1-js/04-object-basics/06-constructor-new/article.md
> +# سازنده ، اپراتور "new"
The spacing for commas should be like this as you have already observed everywhere else:
`سازنده، اپراتور`
instead of:
`سازنده ، اپراتور‍`

2021-03-19 20:31 UTC, mahdyar commented on 1-js/04-object-basics/06-constructor-new/article.md
> +حالا اگر ما بخواهیم که user های دیگری بسازیم، می توانیم `new User("Ann")` ، `new User("Alice")` و ... را صدا بزنیم. این کار بسیار کوتاه تر از استفاده همیشگی از literal ها است، و همچنین برای خواندن آس
The spacing for commas should be like this as you have already observed everywhere else:
`سازنده، اپراتور`
instead of:
`سازنده ، اپراتور‍`

2021-03-19 20:31 UTC, mahdyar commented on 1-js/04-object-basics/06-constructor-new/article.md
> +```smart header="شیءها ، ما بر می گردیم!"
The spacing for commas should be like this as you have already observed everywhere else:
`سازنده، اپراتور`
instead of:
`سازنده ، اپراتور‍`

2021-03-19 20:31 UTC, mahdyar commented on 1-js/04-object-basics/06-constructor-new/article.md
> +# سازنده ، اپراتور "new"
Also using ‍‍`عملگر` instead of `اپراتور` would be better.

2021-03-19 20:31 UTC, mahdyar commented on 1-js/04-object-basics/06-constructor-new/article.md
> +  // شاید شامل منطق و دستورالعمل عجیبی باشد
"Complex" doesn't mean `عجیب`. Perhaps using `پیچیده` would be a better idea.

2021-03-19 20:31 UTC, mahdyar commented on 1-js/04-object-basics/06-constructor-new/article.md
> +اینجا پنهان کردن پرانتزها به عنوان یک "سبک خوب" فرض نمی شود، اما سینتکس طبق خصوصیات مجاز است.
"Omitting" doesn't mean `پنهان کردن`. Perhaps using `حذف کردن` would be a better idea.

2021-03-20 08:42 UTC, mahdiHashemi14 commented
/done

2021-03-20 08:43 UTC, mahdiHashemi14 commented on 1-js/04-object-basics/06-constructor-new/article.md
> +اینجا پنهان کردن پرانتزها به عنوان یک "سبک خوب" فرض نمی شود، اما سینتکس طبق خصوصیات مجاز است.
Thanks for your review🙏🏻

2021-03-20 08:51 UTC, mahdyar approved these changes
Thank you, @mahdiHashemi14!

2021-03-20 08:51 UTC, merged